### ISSUE TITLE
"Plugin Is Broken" Metadata Indentation

### ISSUE THREAD

**Issue by riggsd** [anitagraser/TimeManager#102]
When installing the 1.5.1 release from the upstream plugin repository, the plugin is installed and works correctly.

When working directly from a repository checkout, QGIS complains with the message:

**This plugin is broken**
*Error reading metadata: /Users/driggs/.qgis2/python/plugins/timemanager/metadata.txt*

The problem is incorrect indentation in the `metadata.txt` INI file; specifically, the changelog.

```
changelog=1.5.1
    - fixed #98 Qgis 2.6.1 chrashes after updating Timemanager
1.5
    iterative improvements by https://github.com/carolinux:
    - implemented #78 Add GUI for timestamp label settings
    - implemented #27 Support looping when playing backwards
    - implemented #93 Refactor read/write settings logic
    - updated documentation
    - introduced continuous testing via Travis & test coverage reports via coveralls
    - wrote more tests (postgresql data layers, reading & writing settings)
```

Properly indenting the "1.5" changelog heading fixes the problem.

**Comment by carolinux** [comment]
Can you create a PR for this since you've already fixed it on your machine?
Thanks!
