### ISSUE TITLE
Localization should use QGIS language instead of OS language

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#104]
I have a German OS but use QGIS in English. TimeManager currently shows up in German. It should use the language selected in QGIS settings.

**Comment by carolinux** [comment]
This should be straight forward to change from the __init__ function in timemanager.py . Do you want to do that? You just need to find how to set the lang var in line 47 to the qgs setting.

**Comment by anitagraser** [comment]
I can maybe have a look on the weekend.

**Comment by carolinux** [comment]
Classified it as a feature, since it is not really a bug, it was the intended behavior I had in mind, but I agree it makes more sense to be consistent with the language of QGIS.

**Comment by anitagraser** [comment]
This should do the trick (from statist plugin):

        overrideLocale = bool(QSettings().value("locale/overrideFlag", False))
        if not overrideLocale:
            localeFullName = QLocale.system().name()
        else:
            localeFullName = QSettings().value("locale/userLocale", "")
