### ISSUE TITLE
More than 68 years period problem

### ISSUE THREAD

**Issue by Hq-Ensg** [anitagraser/TimeManager#110]
Hello

Very interesting plugin !

But In my case, I use dates from 1820-01-01 to 2014-01-01.
When I configure the plugin dialog, a message is displayed

Traceback (most recent call last):
  File "C:/Users/xxx/.qgis2/python/plugins\timemanager\timemanagercontrol.py", line 141, in refreshGuiTimeExtents
    MAX_TIME_LENGTH_SECONDS))
Exception: Time length of 6122131200 seconds is too long for QT Slider to handle (integer overflow). Maximum value allowed: 2147483647

Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]
Version de QGIS :
2.6.0-Brighton Brighton, exported

2147483647 value looks like a 31bits value (so -2147483647 -> 2147483647 a 32 bit value)
6122131200 value corresponds to my "almost 200 years" period, converted in seconds.

So in that case, there's a "overflow" limitation. But I don't understand why the plugin works in using always seconds as base information even if the time format is %Y-%m-%d
If the period is > 68 years, sadly it becomes useless.

Additional question : Why is it impossible to use Qdate fields for dates, but only QString fields ?

Thanks
Hervé

**Comment by carolinux** [comment]
I fixed the limitation in the current master of github ( 268af9d439ea899d5) a few weeks ago . See if replacing the plugin code with the code from github fits your needs. The solution was in exactly what you say, that one doesn't need seconds precision always. If you need help using the github version, just write here. Thanks. But basically you'd have to replace the directory "C:/Users/xxx/.qgis2/python/plugins\timemanager " with the content from github.

**Comment by carolinux** [comment]
Also, qdate and qdatetimes in shapefiles are supported (see here in DateTypes: https://github.com/anitagraser/TimeManager/blob/master/query_builder.py) 

 If QGIS converts some data to strings that's a QGIS issue and it probably has to do with how they're imported. If you have a dataset with qdates that doesn't get recognized/handled properly, feel free to share. carolinegr at gmail.com.

**Comment by Hq-Ensg** [comment]
Thanks a lot for this very quick reply !
Github version works much better.
I send you a bug report by email.
Best regards. Hervé
