### ISSUE TITLE
Opening project raises Exception("Unrecognized time frame type : {}".format(timeFrameType))

### ISSUE THREAD

**Issue by ssrebelious** [anitagraser/TimeManager#114]
I have time manager enabled (but I don't use it) and every time I open existing project I get an error. Seems that Timemanager think that it need to work if enabled, but it don't. If I disable Timemanager everything is fine. OS - OpenSUSE 13.1. Here is the Exception:

>An error has occured while executing Python code:
>Traceback (most recent call last):
>  File "/home/yury/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 372, in >setTimeFrameType  raise Exception("Unrecognized time frame type : {}".format(timeFrameType))
Exception: Unrecognized time frame type : 
>
>Python version:
>2.7.6 (default, Nov 21 2013, 15:55:38) [GCC]
>
>QGIS version:
>2.8.1-Wien Wien, exported
>
>Python path: ['/home/yury/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/yury/.qgis2/python', u'/home/yury/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/site-packages/networkx-1.7-py2.7.egg', '/home/yury', '/usr/share/qgis/python', '/usr/lib/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/PIL', '/usr/local/lib64/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/wx-2.8-gtk2-unicode', u'/home/yury/.qgis2//python', '.', '/home/yury/.qgis2/python/plugins/mmqgis/forms', '/home/yury/.qgis2/python/plugins/QuickMultiAttributeEdit/forms', '/usr/share/qgis/python/plugins/fTools/tools', '/path/to/project/latin/no_spaces']

**Comment by carolinux** [comment]
Hey there - not sure what exactly is happening there to be honest. Do you have TimeManager in translated version (non English) ?
I changed the code a bit to log this as a warning instead of having an annoying exception in the commit above.

**Comment by carolinux** [comment]
For me, when I load a project that doesn't have TimeManager information stored in it, TimeManager goes to sleep automatically. ^_^

**Comment by ssrebelious** [comment]
Ok, I downloaded all the files from this repository and replaced the files that were installed using "Manage and install plugins" tool. Now the problem is gone. Thanks!
