### ISSUE TITLE
Archaeological data negative datations

### ISSUE THREAD

**Issue by tonyduky** [anitagraser/TimeManager#115]
First of all thanks a lot to you for developping such a useful plugin for QGIS.

As I mentionned in another "issue", I think a great feature to add to Time manager would be to enable negative datations. A lot of archaeology researchers have to work with negative datations.
So this feature could mean building an animated archaeological phase plan that could work with negative datations.

Another great feature would be for time manager to be able to automatically dim the opacity of points based on time data. For example an artefact having a chronological range from 0 till 100 A.D would appear at 0 and then slowly fade out until 100 when it would have completely disappeared.

I think this would have a very interesting visual effect on a animated archaeological phase plan and it would be a better visual transcription of the artefact chronological range.

Thanks a lot for your work and quick answers!

**Comment by carolinux** [comment]
@anitagraser maybe the opacity effects is something you know more about

**Comment by anitagraser** [comment]
These styling effects are already possible using expression-based styling. Due to the many different potential styles, I don't think this will ever be automatically set by Time Manager.

**Comment by carolinux** [comment]
@tonyduky what kind of support do you need?
Would supporting the following format work? Or do you also need months and day of month this far back in the past? I would assume for archaelogical application putting the year may be enough.
200 BC
199 BC
1 BC
1 AD
5 AD

**Comment by tonyduky** [comment]
For my own database I just used the "-" sign to specify negative dates so i
looks like that

-200
-199
-1
1
5

I personally think it's faster to encode in a database

Anyway thanks alot for working on this :D

2015-05-12 22:50 GMT+02:00 Ariadni-Karolina Alexiou <
notifications@github.com>:

**Comment by carolinux** [comment]
The minus sign is a bit tricky to handle. I'm going to roll out a version that supports the format
"year BC/AD" with Time Manager 1.7. Shouldn't be too hard to convert your data to this format. Stay tuned.
So in your case you don't have month/day information?

**Comment by tonyduky** [comment]
No we usually don't use month/day informations.
Thanks a lot for working on this !!

**Comment by carolinux** [comment]
Hello, please try the current master 399dde4b9c6c300081 and tell me if you find any issues!

Remember that your dates need to have 4 digits + AD/BC If you have for example 20 BC it needs to be written as 0020 BC or if you have 100 AD it needs to be written as 0100 AD

**Comment by carolinux** [comment]
You need to click on the small acropolis button next to the on/off button to enable archaelogy mode

**Comment by carolinux** [comment]
@tonyduky those are for you ^^ (not sure if it sends the email without the mention)

**Comment by tonyduky** [comment]
Thank you very much for making this new feature ! !

I'm gonna try to convert my data and test it on it :D

**Comment by tonyduky** [comment]
Hi, does not seem to work

I tried with a simple data set
1	0352 BC
2	0400 BC
3	0200 BC
4	0200 AD

 and i get this error message : 

Une erreur est apparue lors de l'exécution du code Python :

Traceback (most recent call last):
  File "/Users/Antoine/.qgis2/python/plugins/TimeManager/timemanagercontrol.py", line 262, in toggleAnimation
    expectedNumberOfFrames = self.timeLayerManager.getFrameCount()
  File "/Users/Antoine/.qgis2/python/plugins/TimeManager/timelayermanager.py", line 68, in getFrameCount
    return time_util.get_frame_count(extents[0], extents[1], self.timeFrame())
  File "/Users/Antoine/.qgis2/python/plugins/TimeManager/time_util.py", line 323, in get_frame_count
    years = (end-start).y
  File "/Users/Antoine/.qgis2/python/plugins/TimeManager/bcdate_util.py", line 102, in __sub__
    return self.__add__(-td)
TypeError: bad operand type for unary -: 'BCDate'

Version de Python :
2.7.1 (r271:86832, Jul 31 2011, 19:30:53) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)]


Version de QGIS :
2.8.1-Wien Wien, 

Chemin vers Python : ['/Users/Antoine/.qgis2/python/plugins/pyarchinit/modules/gui', '/Users/Antoine/.qgis2/python/plugins/pyarchinit/modules/gis', '/Users/Antoine/.qgis2/python/plugins/pyarchinit/modules/db', '/Users/Antoine/.qgis2/python/plugins/pyarchinit/modules/utility', '/Users/Antoine/.qgis2/python/plugins/pyarchinit', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing', '/Users/Antoine/.qgis2/python/plugins/processing', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/Antoine/.qgis2/python', u'/Users/Antoine/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', u'/Users/Antoine/.qgis2//python', '.', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools', '/Users/Antoine/Documents/A. Darchambeau/AP/AP GIS']

**Comment by tonyduky** [comment]
I got another error message too : 

An error occured while trying to add layer testtimema to TimeManager.Traceback (most recent call last):
File "/Users/Antoine/.qgis2/python/plugins/TimeManager/timemanagercontrol.py", line 580, in createTimeLayerFromRow
settings, self.iface)
File "/Users/Antoine/.qgis2/python/plugins/TimeManager/timevectorlayer.py", line 66, in __init__
raise InvalidTimeLayerError(traceback.format_exc(e))
InvalidTimeLayerError: 'Traceback (most recent call last):\n File "/Users/Antoine/.qgis2/python/plugins/TimeManager/timevectorlayer.py", line 64, in __init__\n self.getTimeExtents()\n File "/Users/Antoine/.qgis2/python/plugins/TimeManager/timevectorlayer.py", line 158, in getTimeExtents\n start_str, end_str = self.getMinMaxValues()\n File "/Users/Antoine/.qgis2/python/plugins/TimeManager/timevectorlayer.py", line 140, in getMinMaxValues\n minValue= datetime_to_str(min(unique_vals),fmt)\nValueError: min() arg is an empty sequence\n'

Thanks a lot for your help!

**Comment by carolinux** [comment]
Hello, try with a newer version. Please click on the acropolis button to enable archaeological mode. I made a video where I use your data and it works. Where can I send it?

**Comment by carolinux** [comment]
@tonyduky here is a video with the intended usage
https://www.youtube.com/watch?v=7-W98oi__3A&feature=youtu.be

**Comment by tonyduky** [comment]
Hey thanks for your help!

Now, it's working partially.

I tried on mac and pc. Both 2.8.1 Wien and with your last master.

everytime I press the play button i get this message :

Une erreur est apparue lors de l'exécution du code Python :

Traceback (most recent call last):
  File "C:/Users/Tony/.qgis2/python/plugins\timemanager\timemanagercontrol.py",
line 262, in toggleAnimation
    expectedNumberOfFrames = self.timeLayerManager.getFrameCount()
  File "C:/Users/Tony/.qgis2/python/plugins\timemanager\timelayermanager.py",
line 68, in getFrameCount
    return time_util.get_frame_count(extents[0], extents[1], self.timeFrame())
  File "C:/Users/Tony/.qgis2/python/plugins\timemanager\time_util.py",
line 324, in get_frame_count
    years = BCDate.dist(end,start)
NameError: global name 'BCDate' is not defined


Version de Python :
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


Version de QGIS :
2.8.1-Wien Wien, exported

Chemin vers Python : ['C:/Users/Tony/.qgis2/python/plugins\\processing',
'C:/PROGRA~1/QGISWI~1/apps/qgis/./python', u'C:/Users/Tony/.qgis2/python',
u'C:/Users/Tony/.qgis2/python/plugins',
'C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg',
'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk',
'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg',
'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg',
u'C:/Users/Tony/.qgis2//python', '.',
'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis\\python\\plugins\\fTools\\tools']


I click ok then this animation starts.


But it's does not work properly when i try using the "end" feature.


Nothing happens until it's passes 0 and then everything appears and
disappears very quickly.


Thanks a lot for you help and your work as usual :)







2015-05-20 17:58 GMT+02:00 Ariadni-Karolina Alexiou <
notifications@github.com>:

**Comment by carolinux** [comment]
Hello, you don't need to put your system details anymore ^_^ 
So, the first error I fixed, the end feature I need to check again.

**Comment by carolinux** [comment]
If you send me your data it could speed up the process too! Email carolinegr@gmail.com

**Comment by carolinux** [comment]
alright, seems to work, here is another video for posterity
https://youtu.be/uMyJjUfE2tA
