### ISSUE TITLE
Time Manager dock min width should be reduced to absolute minimum

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#118]
In the latest version, the dock window is wider than it used to be. There's always some extra space on the right (besides the dropdown with the frame size type) which makes the dock wider than it has to be. This is a problem on small screens.
![screenshot 2015-04-24 17 44 47](https://cloud.githubusercontent.com/assets/590385/7322647/a3ab7f20-eaa9-11e4-9bd4-d0fb7114f490.png)

**Comment by carolinux** [comment]
Although I can't reproduce the behavior, there is a change in dockwidget2.ui that may have caused this. Let me know if it works better now.

**Comment by anitagraser** [comment]
Thanks, that helped :-)
