### ISSUE TITLE
InvalidTimeLayerError?

### ISSUE THREAD

**Issue by ekehmeier** [anitagraser/TimeManager#119]
Hi Anita,

I'm trying to learn Time Manager so I can complete a project for a professor (not for class, for real life so more pressure). I followed a tutorial about earthquake data and imported my csv into QGIS and saved it as a shapefile, but when I tried to import it into timemanager, I got the following error message: "InvalidTimeLayerError: 'Invalid time layer: To and From attributes must have exact same format'"

I followed every step exactly as shown in the tutorial (https://www.youtube.com/watch?v=nHrFOPf1UGw) so I don't understand what went wrong. What does it mean by to and from attributes?

Another question - I've only seen examples of time manager to represent spatial data, but I'm trying to join year/import $ value data from several regions into the US with the region shapefiles. The only element of the data that is changing from year to year is dollar amount - nothing is moving spatially. Will this still work in time manager? (I've attached an image of the attribute table that i will merge to the region shapefile) I want to symbolize each region layer as a specific color, which gets darker or lighter through the years as the import $ value changes.

one more thing, I don't know much code, just a few basic things in Spatialite

Thank you so much!
Emily
![screen shot 2015-05-13 at 4 52 24 pm](https://cloud.githubusercontent.com/assets/12437013/7623564/9e1e9038-f990-11e4-9d12-26e65ac827e8.png)

**Comment by anitagraser** [comment]
We would need to see your data and time manager configuration to track down the issue. It seems like the datetime formats in the two columns you specified for start and end time is not the same.

Considering your second question. I could write up a tutorial. Would it be possible for you to share the data? It would speed up the process.

**Comment by carolinux** [comment]
Just a year is not in the supported formats yet. Try changing your data so
that it is 1971-01-01. Seconding the request for files and your qgs file so
that we can see what is the issue.

**Comment by anitagraser** [comment]
Wouldn't the year value alone be interpreted as integer?

**Comment by ekehmeier** [comment]
HI Anita,Thank you so much for getting back to me so quickly! I did not
realize I needed to put an end time column - the tutorial example that i
mentioned only specified a start time.

If you would write up a tutorial, that would be better than I could have
ever dreamed! However, if you don't have time for this, I'd appreciate any
form of help. Thank you for being so receptive.

I'll attach my data and explain what the professor wants.

He wants to track the flow of plant material imports into the US (in dollar
value per year) from various ecoregions from 1967-2014. I have a base world
map from NaturalEarth (ne_110m_admin_0_countries.zip)

**Comment by carolinux** [comment]
@anitagraser yes, but an integer means only seconds after epoch currently. I think we should support the option that people say an integer is a year or even a yyyymmdd value (20140101) as I told you in a mail before ;)
@ekehmeier I think it's not possible to attach files on github. I think, you don't have to specify an end column necessarily and if you hadn't it's strange that  you saw the message that you saw. Please send all your files to carolinegr@gmail.com -> your .qgs file and all the data that went into the join.

**Comment by ekehmeier** [comment]
oops, sent without finishing.

continued:

I selected countries to create the ecoregions and dissolved. (region files
attached also)

I also have an csv with the data I want to join to the regions
(tradedata_final.csv)  with 4 columns: region names, year, dollar value,
and the column I edited to have year-month-day. Today after class I'm going
to try to do a many to one join to join this data to my region shapefiles -
i had join the data yesterday but realized it was in the wrong format with
each year as a new column (oops).

There are rows at the bottom of this csv file that say "total" instead of a
region - I will join this to the US shapefile to track the total import
value.

My idea, like i think I said in the post, is to symbolize the regions (once
I get the join done) to increase in color darkerness as the $value
increases, so in years that have 0$ in imports for a particluar county,
that country will be white.

I think I have an idea of how time manager should work and the steps that I
need to take, I just am scared of running into problems like the error
message i posted about. Also, I know that displaying the years on the map
is an option with time manager, but can I also have the dollar value
written out in each country each year?

**Comment by ekehmeier** [comment]
oops just saw this. I'll forward my email with the files to that email!

**Comment by carolinux** [comment]
@ekehmeier  it's unrelated. Please send my your .qgs project file too so that I don't need to figure out exactly how you did the joins. :)

**Comment by anitagraser** [comment]
continuing support via email

**Comment by ekehmeier** [comment]
Hi Anita,

I'm almost done with the time manager project I contacted you about a while
ago. Do you know of any program other than mencoder that i can use to turn
the png files into a video/ I can use mac or pc? I downloaded
mencoder/mplayer but i can't get it to open, also it seems to be very
code-y and confusing and I don't know how to code.

one more thing: sometimes when i play the animation in qgis, the map
disapeears for the last year. sometimes this doesn't happen. do you know
why this would be? Thank you!

Best,
Emily

**Comment by carolinux** [comment]
Hello,
regarding the second question, try changing the timestep from a year to a
month etc and see if this affects the behavior. I think I know what it is,
it has to do with how we determine when to end the animation. I can adjust
it it a newer version

**Comment by anitagraser** [comment]
On win, you can use movie maker by Microsoft. It's free and non-cody.

**Comment by ekehmeier** [comment]
Awesome, thank you for both tips!

**Comment by ekehmeier** [comment]
Hi Anita and Caroline,

I contacted you earlier about problems with getting my project to work with
time manager. since then, it's been working and I've been playing around
with editting the actual shapefiles. Now I'm trying to add them into Time
Manager again to finish up, but it's not working. I keep getting this
message:

​Do have any idea what's happening? I haven't made any changes to the
attributes of the shapefiles, and I've never had problems adding them into
Time Manager in the past. Could it have to do with the column to farthest
to the right in the screenshot below? I don't remember if that was there in
the past:

I don't think there's a problem with the format of the dates in the
attribute tables of my shapefiles, unless requirements have changed in the
updated versions of TM. This is what my date format is:

​[image: Inline image 1]

Thank you for reading my message!

Best,
Emily

**Comment by anitagraser** [comment]
Maybe it's just me but I cannot see the screenshots in your  latest message.

**Comment by carolinux** [comment]
I can't see the screenshot either. Please bear in mind that columns where the name has special (ie, non latin) characters aren't handled correctly by qgis

**Comment by carolinux** [comment]
Also I would double check that all your values have the correct format and you haven't missed say a slash or a hyphen somewhere

**Comment by ekehmeier** [comment]
It don't think that my format is the problem, here are the screenshots
again.

**Comment by carolinux** [comment]
please send an email directly to carolinegr@gmail.com, github doesn't
support attachments

**Comment by ekehmeier** [comment]
oh, ok thank you.
