### ISSUE TITLE
Refresh map when looping through non-geometry CSV

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#120]
The use case is as follows: There's a spatial layer and a CSV layer. The CSV layer contains different values for different times for the geometries in the spatial layer. The CSV layer is joined to the spatial layer.

We can already make TimeManager loop through the CSV layer but the map is not refreshed so while everything else works correctly, the effect cannot be seen on the map.

**Comment by carolinux** [comment]
I don't understand this completely yet. The map is refreshed, but maybe the join isnt?

**Comment by anitagraser** [comment]
Maybe that's the case. Anyway, manually moving the map updates everything. Check the CSV example in the TimeManager google drive folder.

**Comment by carolinux** [comment]
probably a triggerRepaint() is needed

**Comment by carolinux** [comment]
what needs to be repainted is the joined layer with the geometries.

**Comment by carolinux** [comment]
Made it refresh layers who are joined in some way with a timemanaged layer. Hopefully this isn't too heavy !
