### ISSUE TITLE
AttributeError: relativedelta instance has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#121]
Two users at the workshop had the following error:

<pre>Traceback (most recent call last):
  File "C:/Users/MRTR/.qgis2/python/plugins\timemanager\timemanagercontrol.py", line 257, in toggleAnimation
    expectedNumberOfFrames = self.timeLayerManager.getFrameCount()
  File "C:/Users/MRTR/.qgis2/python/plugins\timemanager\timelayermanager.py", line 78, in getFrameCount
    us2 = td2.total_seconds()
AttributeError: relativedelta instance has no attribute 'total_seconds'
 
 
Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]
 
 
QGIS version:
2.8.1-Wien Wien, exported
 
Python path: ['C:/PROGRA~2/QGISWI~1/apps/qgis/./python/plugins\\processing', 'C:\\Users\\MRTR\\.qgis2\\python\\plugins\\GeoCoding', 'C:/PROGRA~2/QGISWI~1/apps/qgis/./python', u'C:/Users/MRTR/.qgis2/python', u'C:/Users/MRTR/.qgis2/python/plugins', 'C:/PROGRA~2/QGISWI~1/apps/qgis/./python/plugins', 'C:\\PROGRA~2\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~2\\QGISWI~1\\bin', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win32.egg', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\python_dateutil-2.2-py2.7.egg', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2014.2-py2.7.egg', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win32.egg', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.6.1-py2.7.egg', 'C:\\PROGRA~2\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:/Users/MRTR/.qgis2//python', 'C:\\Users\\MRTR\\.qgis2\\python\\plugins\\mmqgis/forms', 'C:\\PROGRA~2\\QGISWI~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'D:/Data/QGIS workshop/Shop4/Example_OSM-buildings', '.']</pre>

**Comment by carolinux** [comment]
probably a dateutil version thing. It works fine on 2.2

**Comment by carolinux** [comment]
ah, this was such an obscure issue. relativedelta changed from 1.5 to 2.1 from a python old style class to a python new style class. Apparently type(foo)=relativedelta only works for new style classes so it wasnt getting the frame count correctly.
