### ISSUE TITLE
Interpolation Data limit

### ISSUE THREAD

**Issue by raquel-ucl** [anitagraser/TimeManager#127]
Hi there. Thanks a lot for this plugin, I think it's great! 

However, I don't think I can use it since my DB is huge. It has ship track data for about 35000 ships. Each having from just a few points to hundreds of thousands. I tried using your plugin with 5 average ship tracks, but QGIS quits and I can't see if the problem is I've reached the data limit that your plugin can handle, or something else. Is there any way for me to find out (log file maybe)? Is there any test of data load you've perform and have an idea on how much data can be plotted so that I can re-structure my DB and see if it works?

Cheers,
Raquel

**Comment by carolinux** [comment]
Hello,
are you trying to use it with the interpolation feature or without?

**Comment by raquel-ucl** [comment]
Ah, yeh, sorry, forgot to mention that. I'm trying with interpolation 0:) Without it, it works fine, but I need to draw the path the ships follow.

**Comment by carolinux** [comment]
OK, then that is the reason. I will get around to creating a faster version eventually. The reason the current version doesnt work is that it loads everything into memory. Check back in a few weeks :)

I haven't done a stress test (also it depends on the system), so I can't say for sure where the threshold is. I expect it would work if you had 5 ship tracks with ~100 points each or so.

**Comment by raquel-ucl** [comment]
Ah, OK, thanks a lot for your quick reply, and again thanks for the plugin! :-)

**Comment by carolinux** [comment]
Great! It would be cool if you can tell me how big your database is also in GB so that I have an idea what to test later.

**Comment by carolinux** [comment]
Hello @raquel-ucl.
If you use the current master @ 32a426f , you may be able to use your data. The requirement is that you would need to sort your database according to the timestamp (from older to newer timestamps) and then use the (new) interpolation mode that says that it requires sorted data from the drop down menu. I tried it with an sqlite database and it seems to work. Would love to get feedback from you.

**Comment by raquel-ucl** [comment]
Hi @carolinux! Sorry, I didn't see your previous comment. I'm not sure about how to measure my DB. The one I'm trying your plugin with is 38GB at the moment. However it's for a research project and we are doing several tests, so it might be even bigger or if we resample the data might get smaller, but can't tell how much yet!

I'll test the new version of your plugin and let you know :) Thanks!

**Comment by raquel-ucl** [comment]
Hi again. I have cloned the latest version of the repo (32a426f), but not sure how to build the plugin to install it in QGIS. How can I do that?

**Comment by raquel-ucl** [comment]
Oh wait! I've just seen the instructions in [GITHUB.md](https://github.com/anitagraser/TimeManager/blob/master/GITHUB.md). Never mind :-)

**Comment by carolinux** [comment]
40 GB.. oh lord.. ;) Maybe make a separate table for only a few ship traces (sorted by time) if it doesnt load.

**Comment by raquel-ucl** [comment]
I know, I know :) It's shipping track data and there's many ships, so also many points! We'll resample it, it should get much smaller. At the moment I'm trying to interpolate with your plugin with about 80K points which didn't work in the last version, but works now! Trying with 300K doesn't work though - make my QGIS unresponsive.

**Comment by carolinux** [comment]
yay, progress :)
I think at some point we hit a qgis-specific limit with respect to how it fetches data from data sources. I contribute to qgis as well, I will look into it. 

just to confirm, you're using the third interpolation mode, right? try not to scroll very much and press play instead.

**Comment by raquel-ucl** [comment]
Yes, I chose the third option. I've tried again with the 300K table and it takes about 10 minutes to load and when I try to click the _Play_ button QGIS freezes. I've just looked in the screen again and there's a new point, so something has happened! It seems it's taken 2 frame steps, but I haven't paused it or anything.

**Comment by carolinux** [comment]
Ok, so that means it's super slow. Same in my case. Right now I'd say try
to resample the points (interpolation will help fill the gaps after all)
and I will see what can be done on the core application level.

**Comment by raquel-ucl** [comment]
OK, we'll see how it behaves with less data :) 
Thanks a lot for your help!

**Comment by carolinux** [comment]
closing this for now, the outcome was that now there is an improvement in how much data interpolation can handle.
