### ISSUE TITLE
New functionality: Accumulative visualization

### ISSUE THREAD

**Issue by raquel-ucl** [anitagraser/TimeManager#129]
Hi!

I was wondering if you are planning to visualise not only the points inside each current time step, but the accumulation from the first step to the current one? For example, if you are visualising a path, it'd be nice to have no only the position in each time frame separately, but see the previous positions too. For example, something like [this plugin for LeafLet](http://dwilhelm89.github.io/LeafletSlider/) (move slider on top right to see behaviour).  Or something like [this other plugin for CartoDB](http://bl.ocks.org/iriberri/raw/7335eebcdda69b0b4f80/) which also filters points for the selected time period.

Cheers,
Raquel

**Comment by carolinux** [comment]
If you have the newest version, you can see that the end time can be selected as "none-accumulate features". Not meant to work with interpolation though. But maybe it's still useful to you.

**Comment by carolinux** [comment]
there was a related issue here which I closed 2 hrs ago
https://github.com/anitagraser/TimeManager/issues/126

**Comment by raquel-ucl** [comment]
You are very right. It works very nicely :) Thanks!
