### ISSUE TITLE
"No module named raster.cdflayer" error

### ISSUE THREAD

**Issue by haojiezhu** [anitagraser/TimeManager#130]
TimeManager 2.1 throws out "No module named raster.cdflayer" error upon activation on both Windows and FreeBSD. I tried to recompile GDAL with NetCDF support on FreeBSD and still can't solve the problem. Is there any third-party library that needs to be installed? I am using QGIS 2.10 (latest release, not 2.1).

**Comment by carolinux** [comment]
Hey there, try 2.1.1 from the repo.

I was missing an __ init __ .py

**Comment by haojiezhu** [comment]
Thanks, it works now.

**Comment by carolinux** [comment]
Excellent, thanks for reporting this!
