### ISSUE TITLE
Consider WMS-T support?

### ISSUE THREAD

**Issue by drf5n** [anitagraser/TimeManager#132]
Per http://anitagraser.com/2011/06/10/wms-t-support-in-geoserver-and-mapserver/ Mapserver ( and now GeoServer) both serve WMS-T data.  My particular use-case is a set of storm-surge inundation layers with water level thickness and extents with spatial and time resolutions of 10m and 6 minutes.

What would it take to add raster support for a WMS-T layer to Time Manager?

**Comment by carolinux** [comment]
Hello @drf5n, WMS-T layer support sounds like it would require quite a bit of work but it can certainly be incorporated into the existing software. I have been thinking for a while about introducing the option of having the development of some non-core features "sponsored" by the people who request them. If this is of interest to you please email me at carolinegr@gmail.com. Otherwise you are welcome to (a) implement this yourself and ask me for feedback or (b) wait until I pick this request up in the future

**Comment by anitagraser** [comment]
I think WMS-T support has to go into core first https://hub.qgis.org/issues/13085

**Comment by drf5n** [comment]
Thinking out loud, but not committing to anything....

Maybe the first bit of underlying work would be enabling a time-aware WMS layer, perhaps copying/deriving one from an already discovered WMS / 'contextualWMSLegend' layer and then mangling the URL to maintain a time=??? parameter.

http://dev.openlayers.org/examples/wmst.html provides an example WMS-T service ( http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?service=wms&version=1.3.0&request=GetCapabilities ) which can be discovered directly in QGIS from Layer/Add layer/Add WMS/WMTS Layer/New/URL = http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi  Then choose the 'nexrad-n0r-wmst' layer to 'Add'.  In QGIS, then the layer/properties gives 'Layer source'='contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/png&layers=nexrad-n0r-wmst&styles=&url=http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi'

This chunk of qgis python console adds the layer directly:

    urlWithParams = 'url=http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi&format=image/png&layers=nexrad-n0r-wmst&styles=&crs=EPSG:3857'
    rlayer = QgsRasterLayer(urlWithParams, 'radar WMST', 'wms')
    QgsMapLayerRegistry.instance().addMapLayer(rlayer)

But this code isn't quite right for the OpenLayers sample time of 2005-08-29T14:00:

    urlWithParams = 'url=http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi&time=2005-08-29T14:00&format=image/png&layers=nexrad-n0r-wmst&styles=&crs=EPSG:3857'
    rlayer = QgsRasterLayer(urlWithParams, 'radar WMST time', 'wms')
    QgsMapLayerRegistry.instance().addMapLayer(rlayer)

**Comment by carolinux** [comment]
I agree that this needs support from core, like #57

**Comment by drf5n** [comment]
Doesn't anything that supports WMS already support extra-dimensional queries if the dimensions are placed early enough in the URL?

**Comment by carolinux** [comment]
Didnt you say that specifying the time in the url doesn't work?

**Comment by drf5n** [comment]
Yes, but that might be because I don't know how to specify a prefix URI with optional parameters to QGIS correctly.    Or maybe QGIS's WMS client is discarding or munging the prefix-specified parameters.  The server end of things supports it.  A WMS client shouldn't mess with the given prefix, and if you give the client a prefix like "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?time=2005-08-29T14:00&" or http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?time=2005-08-29T14:00&DIM_planet=earth&DIM_eon=orduvician&" it should keep those as part of the prefix of the URI it uses to access the server, just as it should keep http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/planet/earth/eon/orduvician/time/20050829T140000/n0r-t.cgi?"    It seems like QGIS's WMS ignores the parameters in the WMS prefix and builds the URLS for accessing the layers from scratch.

**Comment by drf5n** [comment]
This sample server supports WMS-T.  Below are a WMS and GetCapabilities link:

    http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?TIME=2005-08-29T13:10:00Z&LAYERS=nexrad-n0r-wmst&TRANSPARENT=TRUE&FORMAT=image%2Fpng&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=&SRS=EPSG%3A4326&BBOX=-112.5,22.5,-85,45&WIDTH=256&HEIGHT=256 

http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?TIME=2005-08-29T13:10:00Z&LAYERS=nexrad-n0r-wmst&TRANSPARENT=TRUE&FORMAT=image%2Fpng&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities

**Comment by drf5n** [comment]
I can get a specific time from this  WMS-T server into QGIS by using a URL string like the below in Layer/Add WMS/WMTS layer/New/URL :

    http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?TIME=2005-08-29T13:10:00Z&LAYERS=nexrad-n0r-wmst&TRANSPARENT=TRUE&VERSION=1.1.1&

Then check the 'Ignore GetMap/GetTile URI reported in capabilities' and 'Ignore GetFeatureInfo URI reported in capabilities' to use the given URI as a prefix, then choose OK, Connect, and choose the 'nexrad-nor-wmst' layer, and you'll get a radar image of Katrina in New Orleans, USA.

The WMST dataset covers from 1995 to present with 5 minute resolution, so I think it could be a good test-case for WMST coverage.  From the capabilities:

    <Extent name="time" default="2006-06-23T03:10:00Z" nearestValue="0">1995-01-01/2015-12-31/PT5M</Extent>

**Comment by drf5n** [comment]
QGIS core WMS currently supports  WMS-T, and can update them in the console:

    urlWithParams = 'IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/png&layers=nexrad-n0r-wmst&styles=&url=http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?TIME%3D2005-08-29T13:10:00Z%26LAYERS%3Dnexrad-n0r-wmst%26TRANSPARENT%3DTRUE%26VERSION%3D1.1.1%26'

    urlWithParams2 = 'IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/png&layers=nexrad-n0r-wmst&styles=&url=http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?TIME%3D2005-08-29T06:10:00Z%26LAYERS%3Dnexrad-n0r-wmst%26TRANSPARENT%3DTRUE%26VERSION%3D1.1.1%26'

    rlayer = QgsRasterLayer(urlWithParams, 'radar WMST timeV2', 'wms')
    QgsMapLayerRegistry.instance().addMapLayer(rlayer)

    #update to different time
    rlayer.dataProvider().setDataSourceUri(urlWithParams2)
    rlayer.dataProvider().reloadData()
    rlayer.triggerRepaint()

A couple screen-caps from this code are at 
http://gis.stackexchange.com/questions/34667/does-qgis-have-wms-t-wms-with-time-support/153709#153709 

I'm not sure if QGIS core delivers the times (and other dimensions) from the GetCapabilities documents.

**Comment by carolinux** [comment]
Alright, that's pretty great I think. A question, do you know if the types of the times can vary?
In the link you show I see the time format:
2005-08-29T06:10:00Z
but there may be others.

**Comment by carolinux** [comment]
Hey @drf5n, I made a skeleton of the implementation (without UI yet). Please comment on the code directly where there are comments. Main questions are:
(1) Can the data format vary (didn't look at wmst standard extensively)
(2) Can we do range queries on the time?
(3) How would you get the minimum time that exists and the maximum time that exists?

If you've experimented with this getCapabilities thing let me know

**Comment by carolinux** [comment]
Regarding 3, I saw that there is this string you can get from the XML that you have also posted above.
```
<Dimension name="time" units="ISO8601" default="2006-06-23T03:10:00Z" nearestValue="0">1995-01-01/2015-12-31/PT5M</Dimension>
```

Do you know if it's always formatted like this? Ie the Dimension<time> tag contains the information and the text information is of the form startdate/enddate/interval ?

**Comment by drf5n** [comment]
From Appendix C of the WMS spec 1.3 from http://www.opengeospatial.org/standards/wms 

1) the date format can vary, though if it has time components, it should specify a timezone, like 'Z'

Samples:

    ccyy-mm-ddThh:mm:ss.sssZ
    ccyy Year only
    ccyy-mm Year and month
    ccyy-mm-dd Year, month and day 
    ccyy-mm-ddThhZ Year, month, day and hour in UTC 

2) Range queries are like this:

    A single moment (scalar value): 2000-06-23T20:07:48.11Z
    Quarterly data (comma-separated list): 1999-01-01,1999-04-01,1999-07-01,1999-10-01
    Daily data taken at noon since 15 April 1995 (periodic interval): 1995-04-22T12:00Z/2000-06-21T12:00Z/P1D
    Current data refreshed every 30 min (periodic interval): 2000-06-18T14:30Z/2000-06-18T14:30Z/PT30M

3) The min/max come from the getCapabilities document, some examples of time with other dimensions are:

    <Dimension name="time" units="ISO8601" default="2003-10-17">1996-01-01/2003-10-17/P1D</Dimension>
     <Dimension name="temperature" units="Kelvin" unitSymbol="K" default="300">230,300,400</Dimension>
     <Dimension name="elevation" units="CRS:88" unitSymbol="m" default="0">0/10000/100</Dimension>

The can also do a comma-separated list, or a comma-separated lists of ranges.

I don't know that you could count on the values in the dimension string to be sorted.

**Comment by carolinux** [comment]
Alright, by parsing the dimension tag and the default value one can infer
the time type (1) and the min/max values(3). I also took a look at the
standard and it seems a range query is simply TIME=start/end.

I won't support comma separated lists of ranges for now for getting the min
max.

Url of the specs : http://portal.opengeospatial.org/files/?artifact_id=14416

**Comment by drf5n** [comment]
For the query, multipleValues would be more complicated, and I'm not sure that QGIS could make use of a multiple-valued raster, like an AVI or looping GIF.   I think TIME=start and TIME-start/end is fine.  I think the WMS 1.3.0 standard defaults to no multiple queries unless multipleValues is non-zero.

I'd sort of think it would be nice to be able to populate the min/max and maybe interval by trying to parse the GetCapabilities Dimension string, but then be able to modify the derived extents manually--Sort of like in setting the rasterlayer/Properties/Style/color map/ min,max, and number of classes.  if you like that, initially, you could leave out the getcapabilities parsing and use only user-supplied start, end, and interval values.

Thinking of this in terms of use-cases of the million layers of NEXRAD radar WMST, one might want to work with only a short series of hourly data during a 15 day storm, or maybe 5 minute data across a couple hours at landfall.

**Comment by carolinux** [comment]
Alright, this works kindof (without parsing anything from the capabilities)
This is an animation I made:
http://postimg.org/image/nvoqb9uc5/
Basically you go add the wmts layer, you go to add raster and you put start time:
2005-08-29T06:10:00Z
and end time:
2005-08-29T13:10:00Z

Then it will use your defined start and end time. I don't support any other formats than 2005-08-29T06:10:00Z right now, but the example dataset works. Use the branch animation_support if you want to play with the feature.

**Comment by drf5n** [comment]
Cool. It looks like the animation_support branch is merged into the master now.

To get to http://postimg.org/image/nvoqb9uc5/  one would:

I'm afraid I wasn't able to duplicate your animation.    I'm seeing updates as time manager runs, but the updated image remains the default time slice.

Do you add the nexrad-n0r-wmst layer from the WMS server as:   

    http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi

or as something with a TIME= string embedded in it?

And do you add the WMS layer with the IgnoreGetMap/GetTile URI reported in capabilities checked or unchecked?

Also, does the Layer/Properties/General/Layer Source box update with the times controlled by TimeManager?

Thanks for working on this.

**Comment by carolinux** [comment]
I'm going to write a blogpost about it  and another data format in a few
days.

**Comment by drf5n** [comment]
Thanks.

From the code and a couple couple experiments, I found these answers:

1) The code prepends the ignore capabilities URI codes and appends TIME=... value per https://github.com/anitagraser/TimeManager/commit/aeb1542c3c7a7c42d880f032294ebef5026eb34c#diff-cd6b22486bbc55926babb449f52279adR59  The WMS ignores earlier TIME definitions and uses the last one.

2) The Layer/Properties/General/Layer Source (and the layer mouseover text) in the QGIS UI do not appear to be updated when the setDataSourceUri() and triggerRepaint() are called.  The actual data source from the code below is not reflected in the GUI mouseover or the layer/properties. 

    rly=QgsMapLayerRegistry.instance().mapLayersByName("wmst1") 	
    dp=rly[0].dataProvider()
    dp.dataSourceUri()
    u'IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/png&layers=nexrad-n0r-wmst&styles=&url=http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?TIME=2005-08-29T06:10:00Z/2005-08-29T11:10:00Z'

3) I was able to get it to work.  I used 'http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi' as the WMS url, took the defaults and chose 'nexrad-n0r-wmst' as the layer to add.  I'm not sure what I was doing wrong before.

Also, if you use a TimeManager 'Time frame size' spanning several time slices, this WMS overlays them together.  If you use too short of a framesize, the TIME=start/end doesn't span a timeslice and you get a null result. 

This WMST capability of Time manager is really cool.   Thanks a lot!

It might be nice to specify the interval/TimeFrameSize for the WMST query separately than the animation step interval.   In the NEXRAD use-case, it would enable one to get hourly snapshots of the dataset, rather than hourly stacks of the intervening 10 dataset images.

**Comment by drf5n** [comment]
For reference on the nexrad WMS-T service, it looks like they deliver it with mapserver with the  configuration here:  http://mapserver.org/ogc/wms_time.html#example-of-wms-t-with-postgis-tile-index-for-raster-imagery

**Comment by ruhri** [comment]
At first I like to thank you for your work, it's absolutely awesome to see such a development as your plugin, but also QGIS itself and the whole QGIS-ecosystem. It becomes more and more competetive to some major actors on the GIS-stage...
I tried the new wms-t function - knowing that Capabilities-parsing is not included yet - and it generally worked well with our own multitemporal aerial-image web-map-service (http://geodaten.metropoleruhr.de/dop/dop?   ]2006-2014; 1-year-steps]).
Some things to consider should be, that there are different views on temporal data, e.g. to have a look at a specific single point in time (and not a range with from/to), and that there are also cases with reduced accuracy in time (-units) - as our wms; in our use case it's a good method to have time-resolution on an annual base...

http://docs.geoserver.org/latest/en/user/services/wms/time.html
http://mapserver.org/ogc/wms_time.html#example-of-wms-t-with-postgis-tile-index-for-raster-imagery

I know it's somewhat tricky to implement all those cases - we supported the development of dimension-/time-handler-plugin for mapbender3-webGIS.

Maybe I can help with testing your extension; is there anything more I can supply for further development?

**Comment by carolinux** [comment]
Hello @ruhri, I am glad you can use the existing functionality. You can use a yearly time step in time manager, if that's what you're referring to.

  At the moment, I am not planning to develop the WMS-T capabilities further. If you are with a company, consider talking to your supervisors about contracting me for a few hours to implement the exact additional functionality you want. My email is carolinegr@gmail.com

**Comment by drf5n** [comment]
Hi @carolinux.  Did you write the blogpost somewhere?  I'd be interested in reading it.

**Comment by carolinux** [comment]
I'm in the process of writing it. Will notify you.

**Comment by carolinux** [comment]
@drf5n 
Here it is:
http://anitagraser.com/2015/08/04/using-timemanager-for-wms-t-layers/

**Comment by ruhri** [comment]
Dear Carolinux,

thanks for your efforts till now! I’ll forward this to my colleagues and supervisors…
I hope, that we get it done – IMHO it would be an very useful development.

Regards Ben aka “ruhri”

Mit freundlichen Grüßen
Im Auftrag

Benjamin Schepers


Luftbild und Geoinformationssysteme
Kronprinzenstraße 35
45128 Essen
Fon: +49 201 2069-232
Fax: +49 201 2069-400
schepers@rvr-online.de

[cid:image001.jpg@01D0E162.D1577A00]

Die Regionaldirektorin
Kronprinzenstraße 35
45128 Essen
Zentrale: +49 (0) 201 2069-0
Fax: +49 (0) 201 2069-500
www.metropoleruhr.de

Postfach 10 32 64
45032 Essen

Steuernummer: RVR 112/5797/0116
USt.-ldNr.: DE 173867500

Diese E-Mail koennte vertrauliche und/oder rechtlich geschuetzte Informationen enthalten.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail sind nicht gestattet.
This e-mail may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail.
Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
Von: Ariadni-Karolina Alexiou [mailto:notifications@github.com]
Gesendet: Montag, 10. August 2015 17:13
An: anitagraser/TimeManager
Cc: Schepers, Benjamin
Betreff: Re: [TimeManager] Consider WMS-T support? (#132)


@drf5n<https://github.com/drf5n>
Here it is:
http://anitagraser.com/2015/08/04/using-timemanager-for-wms-t-layers/
