### ISSUE TITLE
load SpatiaLite views duplicates information.

### ISSUE THREAD

**Issue by 2cbarata** [anitagraser/TimeManager#135]
I have two tables in SpatiaLite (one with geographical points and other alphanumeric), then I make a view to represent a relation 1 to n, the problem is that when I load the view several times to represent different variable the information on time manager appears duplicated (img 1).
It happens the same situation if I create various views in SpatiaLite and try to load all in the time manager (img 2).
Qgis version: 2.10.0
Time Manager version: 2.1.1
(img 1)
![image](https://cloud.githubusercontent.com/assets/1490248/8542759/b911e0e6-248f-11e5-809b-b5c9fa545716.png)
(img 2)
![image](https://cloud.githubusercontent.com/assets/1490248/8542952/5c0e1fde-2491-11e5-9460-cc11b005f409.png)

**Comment by carolinux** [comment]
Alright, we havent come across this usecase before. I will look into that. Probably has to do with the fact that those views have the same id

**Comment by 2cbarata** [comment]
When I try to load one second layer, in the combo box, the layers appear duplicated.
I can send the SpatiaLite to test if you want

![image](https://cloud.githubusercontent.com/assets/1490248/8547994/438eb5da-24ba-11e5-8c74-09ad2ed899b7.png)

**Comment by carolinux** [comment]
Yes, and please send me the qgs project file as well. carolinegr@gmail.com
(github doesnt support attachments)

**Comment by carolinux** [comment]
Fix for this will be shipped with next release. For now, adding each layer separately (ie by closing the options) and then clicking settings again to add the next layer should work.
