### ISSUE TITLE
on the possibility to define the Settings from the python console

### ISSUE THREAD

**Issue by PiRJJP** [anitagraser/TimeManager#136]
rather than defining interactively the 'Settings' of the QGIS Time Manager plugin, I would like to have the possibility to set them using the python console. This would save a lot of time in case one wants to animate a long list of rasters. Any hint on how to achieve this would be very much appreciated.

PiRJJP

**Comment by carolinux** [comment]
Hello there. This is how you can do it:
'''
from timemanager import layer_settings as ls
from timemanager import timevectorlayer
from timemanager import timerasterlayer

tlm = qgis.utils.plugins['timemanager'].getController().getTimeLayerManager()
settings = ls.LayerSettings()
settings.layer = iface.activeLayer()
settings.startTimeAttribute = "T"
settings.endTimeAttribute = "T"
timeLayer = timevectorlayer.TimeVectorLayer(settings, iface)
tlm.registerTimeLayer(timeLayer)
# now the layer has been added
'''
You can check the class of layer settings for more settings you can set (they all have reasonable defaults - the time format, for instance is initally set to 'pending' which means it will be inferred automatically when it's registered). https://github.com/anitagraser/TimeManager/blob/master/layer_settings.py

Also, keep in mind, you may have to write timemanager as TimeManager in the imports and  the qgis.utils.plugins['timemanager'] call.

Also, if you need any of the more special raster subclasses I have added recently, you'd need to create objects from that class to add to the timemanager.
https://github.com/anitagraser/TimeManager/tree/master/raster

**Comment by carolinux** [comment]
Also,
to get all the layers from qgis
```
allLayers = QgsMapLayerRegistry.instance().mapLayers()
```
Check this file here: https://github.com/anitagraser/TimeManager/blob/master/qgis_utils.py
for more functionality that uses the qgis python bindings directly.

**Comment by carolinux** [comment]
@PiRJJP closing this now. Will reopen it if you have more questions.
