### ISSUE TITLE
Not correctly interpreting time stamp in netcdf file

### ISSUE THREAD

**Issue by aaschwanden** [anitagraser/TimeManager#137]
Hi,

The TimeManager and its ability to work with netcdf files is some of the most useful plugins for QGIS!

I'm not sure if this is a bug:

When I load a CF-conform netcdf file with a gregorian_proleptic calendar, and click on "Layer is netcdf file with time dimension, the TimeManager appears to interpret the time axis incorrectly. That is, it interprets the the as covering 1970-2-01 through 1992-12-31 instead of 1989-1 through 2012-1-1 (e.g. ncview shows the time correctly).

A minimal example can be found here: https://www.dropbox.com/s/njumv7ym9vnqxgm/foo.nc?dl=0

![qgis-netcdf-time](https://cloud.githubusercontent.com/assets/120698/9241938/b1733a84-4126-11e5-8395-b17177ff9ac4.png)

Tested with QGIS 2.10.1

**Comment by carolinux** [comment]
Hello,
thanks for sending in a sample. The problem is that the netcdf file uses an unexpected epoch. There is a way to fix this without me changing anything in the code. After you have added the netcdf to TimeManager, and while still being in the Time Manager settings menu, modify the offset from 0 to 599616000 (this is the difference between 1970 and 1989)

See this screenshot:

http://imgur.com/XAbPh0Q

**Comment by aaschwanden** [comment]
Thanks, this works for me. (Though I'm not sure what you mean with "unexpected epoch").

Do you have any plans to integrate the TimeManager into the Print Composer? This would allow to make really cool animations. Exporting each frame to a png, gif or jpg (as supported in the TimeManager now) seems desirable over directly exporting a movie.

Great work!

**Comment by carolinux** [comment]
Generally, when people talk about epoch in computer time, they mean 1970. NetCDF doesn't abide by this convention, which is fine, but unexpected. :)
https://en.wikipedia.org/wiki/Unix_time

Would be cool if you can share an animation you made with this. 
It's already possible to export just the frames - clicking on the export video gives you this choice. Perhaps it should be named  simply 'Export' instead.

I don't know a lot about print composer, care to tell me what it is?
Thanks :-)

**Comment by aaschwanden** [comment]
Ah, I understand now. I usually think more in a netcdf than a linux context.

Here's some background:

I'm a co-developer of the open-source Parallel Ice Sheet Model (http://www.pism-docs.org). The model produces CF Convention conforming netcdf files. As the model is used for several purposes ranging from paleo-climate simulations, hindcasts of the past decades, to theoretical work, the associated calendar (attribute "calendar" varies in the netcdf file, e.g. "gregorian_proleptic", "365_day", "360_day"). So my guess is that the TimeManager would need to use a python module such as the netcdftime module from the netcf4python library (https://github.com/Unidata/netcdf4-python).

Anyway, regarding your question about the Print Composer:

The Print Composer in QGIS lets you put together maps, add scale bars, annotations, colorbars, etc. and then output in various graphics formats:

![qgis-print-composer](https://cloud.githubusercontent.com/assets/120698/9420252/d9d7a54c-480f-11e5-8012-ad51284e42f9.png)

So if it were possible to integrate the TimeManager into the Print Composer, one would be able to create animations with figures like this

![qgis-pc-exported](https://cloud.githubusercontent.com/assets/120698/9420289/42aa44d0-4810-11e5-9d4d-112b88707f00.png)

instead of the "plain" main window:

![qgis-main-window](https://cloud.githubusercontent.com/assets/120698/9420275/2ab6d8d4-4810-11e5-8966-5474472ebe8f.png)

Alternatively, I have considered writing QGIS python code that loops over the time slices in the netcdf file, calls the Print Composer, and exports the figure, then moves to the next time slice. While I'm reasonable proficient in python, I'm still too unfamiliar with the python bindings of QGIS to pursue this options.

I'm just throwing this out here, maybe other QGIS user would be interested in such functionality.

Cheers,

Andy

**Comment by carolinux** [comment]
Ok, this looks pretty interesting. I can look into that when I have the
time. Right now you can only add labels on timemanager, but being able to
customize the export with graphs etc would enable you to export something
really polished.
