### ISSUE TITLE
Perform functionality tests

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#14]
Before the beta can be released, we should perform basic functionality tests. 

 Data sources that should be included in the tests: 
Shapefiles 
PostGIS 
Spatialite 
KML? 

 The following should be checked: 
handling of NULL values 
handling of invalid data in timestamp attributes 
support of all valid (= supported by the plugin) timestamp formats

**Comment by carolinux** [comment]
More work can be done on this. We now have tests for shapefiles and spatialite layers.
