### ISSUE TITLE
NET_CDF time#units=minutes since 1970-01-01 00:00:00 unsupported

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#140]
The value is interpreted as seconds instead of minutes. No warning is shown.

**Comment by carolinux** [comment]
this is not a bug, it's just unsupported for now

**Comment by carolinux** [comment]
this would be very easy to fix in file https://github.com/anitagraser/TimeManager/blob/master/raster/cdflayer.py
method extract_time_from_bandname
just check if it contains the text seconds or minutes and adjust accordingly

**Comment by carolinux** [comment]
There you go. :-)
Feel free to update the readme that we don't support every possible NetCDF format.

**Comment by anitagraser** [comment]
Maybe we should check for a list of known NetCDF formats and otherwise display a warning? The warning could tell the user that we're assuming a default unit (seconds?) since the specific format is not supported (yet).

**Comment by carolinux** [comment]
Right. Right now minutes and seconds should work though, with epoch 1970.

**Comment by anitagraser** [comment]
Are you testing with the cloud rasters we used as an example dataset in Nodebo? I just checked the netcdf timestamp functionality and found that 1) the dates in the filenames seem to be wrong, should be in 2008, one month steps 2) the animation doesn't work (all layers stay visible) when the netcdf info is used (while it works with the names)

**Comment by carolinux** [comment]
No I tested with some other dataset . Didnt even know those had time info.
I tested with a multi band netcdf. I dont think this will work.
Bests,
Karolina
Στις 22 Σεπ 2015 9:29 ΜΜ, ο χρήστης "Anita Graser" <notifications@github.com>
έγραψε:

**Comment by carolinux** [comment]
Somehow I didnt think of the case where the layer has just one band. live and Learn about data formats, I guess.

**Comment by anitagraser** [comment]
Oh I see. I guess that's also the reason why there's an error message which forces singleband pseudocolor .... Because, by default, the rasters lload with singleband gray and that should be just fine, but TimeManager refuses to work with them.

**Comment by carolinux** [comment]
I did this feature specifically for multi band rasters. It can be adapted
probably to support data like the cloud dataset. Single band gray makes it
hard to work with bands although I dont remember the specifics.
Στις 22 Σεπ 2015 10:24 ΜΜ, ο χρήστης "Anita Graser" <
notifications@github.com> έγραψε:

**Comment by anitagraser** [comment]
Are you using clouds.nc from the testdata folder or a different file? If different, could you commit it or mail it to me? Thanks.

**Comment by carolinux** [comment]
making a new issue
