### ISSUE TITLE
Postgis view and TimeManager

### ISSUE THREAD

**Issue by otarawai** [anitagraser/TimeManager#141]
Hi Anita,

You are doing a wonderful job within the QGIS community. Thank you. 

I have installed TimeManager and can easily run a temporal geospatial visualisation using a PostGIS point layer directly from a Postgres 9.4 database. If I create a database view across the same base table point data, and then import the view layer into QGIS I am not able to use TimeManager for a simple temporal visualisation. Is this expected behaviour or did I miss something?

Thank you,
Julian

**Comment by anitagraser** [comment]
Hi Julian,
Views should work. They might be slower but that's all. I'll try with the latest version and report back.

**Comment by anitagraser** [comment]
I've tested it here and it works as used to. Please provide more details about the table (schema), view (schema) and Time Manager settings, so we might be able to reproduce the issue.

**Comment by anitagraser** [comment]
Closing for lack of feedback. Reopen if necessary.

**Comment by otarawai** [comment]
Sorry Anita for not commenting sooner - yes I have database views working thru timemanager now. I re-installed timemanager and visualisations started working. 

Thank you
