### ISSUE TITLE
support for singleband netcdf files with time attribute

### ISSUE THREAD

**Issue by carolinux** [anitagraser/TimeManager#142]

**Comment by carolinux** [comment]
@anitagraser the netcdf dataset with the clouds that we used in Nodebo should work now

**Comment by anitagraser** [comment]
Thanks, now it works great! What's the reason for requiring QGIS >= 2.10? It's ok, just wondering in case somebody at the workshop (only QGIS 2.8 installed) asks.

**Comment by carolinux** [comment]
That's for the multi bands . I exported the set Band function to the python
API for the 2.10 release
Στις 23 Σεπ 2015 7:38 ΜΜ, ο χρήστης "Anita Graser" <notifications@github.com>
έγραψε:

**Comment by anitagraser** [comment]
Great, thanks!
