### ISSUE TITLE
Ensure HiDPI support for all GUI parts

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#143]
The following dialogs need some love since labels are cut off on HiDPI displays:

![image](https://cloud.githubusercontent.com/assets/590385/10051731/487329fe-6223-11e5-9fd3-29782a1ea58a.png)

![image](https://cloud.githubusercontent.com/assets/590385/10051743/5d8c92b2-6223-11e5-93b2-4f95af062a14.png)

**Comment by carolinux** [comment]
Alright, are you on it? I don't have a device to test that at the moment.
Στις 23 Σεπ 2015 7:47 ΜΜ, ο χρήστης "Anita Graser" <notifications@github.com>
έγραψε:

**Comment by anitagraser** [comment]
I will, but might take a while. I have to learn about this issue first.

**Comment by anitagraser** [comment]
Label dialog was fixed in https://github.com/anitagraser/TimeManager/commit/d7098595230c7c648fcc561fbdc31abf86aaf6d3

**Comment by anitagraser** [comment]
Video export dialog was fixed in https://github.com/anitagraser/TimeManager/commit/2fa9336afab0b2f04b56f1cd39e7e6b8fe133f26

**Comment by anitagraser** [comment]
The biggest remaining issue are the small image buttons for start/stop and archaeological mode 

[OpenScienceEU.pdf](https://github.com/anitagraser/TimeManager/files/966168/OpenScienceEU.pdf)

**Comment by anitagraser** [comment]
Oh, archaeological dialog also needs a face lift

![arch-dialog](https://cloud.githubusercontent.com/assets/590385/25557605/334e48a6-2d15-11e7-89ed-e2eabf437dfb.png)

**Comment by anitagraser** [comment]
Arch dialog was fixed in https://github.com/anitagraser/TimeManager/commit/8c6e21fcb5f8aa643a6d198feabcb9ab6994b30d
