### ISSUE TITLE
convert -h return code is 1

### ISSUE THREAD

**Issue by sina-masoud-ansari** [anitagraser/TimeManager#146]
Just fyi, I'm trying to export an animation but get stuck when checking for convert. The code is checking for return code of 0 but on my distribution return code from 'convert -h' is 1. convert -version returns 0 though.

Cheers

covert -h
echo $?
1

covert -help
echo $?
1

convert -version

Version: ImageMagick 6.8.9-9 Q16 x86_64 2015-01-06 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib

echo $?
0

lsb_release -a

Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

**Comment by sina-masoud-ansari** [comment]
By the way, thanks for the great plugin!

**Comment by carolinux** [comment]
fixed by #147
