### ISSUE TITLE
Unstable/erratic display of points

### ISSUE THREAD

**Issue by bschiltz** [anitagraser/TimeManager#153]
Hello,

I am having trouble getting the TM plugin to work. I am using QGIS 2.10.1 and TM 2.2.1. I have tried searching for answers and asking on [GIS.stackexchange](http://gis.stackexchange.com/questions/172562/qgis-time-manager-2-2-1-does-not-display-any-points) but got no response. I have data collected from GPS collars on cows between about July 20, 2015 and Oct 30, 2015. Points were taken at 10 minute intervals and I have made sure time formats are written in the correct format (yyyy/mm/dd hh:mm). Initially I loaded the data in as a .csv file, then exported it as a shapefile through QGIS. When I enabled TM and added the layer, all points disappeared as expected. When I click the play button I can see the time stamp progressing at the specified interval (I've tried everything from 1 hour to 1 day) but no points display until nearly the end of the data (usually around October 5, but it is erratic) and only some points within that period display.

The full data set contains about 200,000 records, so I tried breaking it apart by each GPS collar as well, but that yielded the same results, i.e. only displaying some points near the end of the time span.

Today I tried loading the data into PostGIS and using that database in QGIS but the same behavior persisted. I also found the log messages and it throws this error when I add in the layer:
2	unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'

Finally, I tried making up some simple test data just to confirm the plugin is functioning but it seemed to totally fail. Here are screenshots of what I did with the test data.

http://i.imgur.com/7CeZrkp.jpg
http://i.imgur.com/NVQfuDd.jpg
http://i.imgur.com/5f39EIe.jpg
http://i.imgur.com/0ttjr4S.jpg

When I click play for this data, the time stamp and slider progress at the specified interval (I tried 1 day, 2 days, 1 week, etc.) but no points show up at all. 

I am a complete loss here. If you would like to see additional screenshots or a copy of my data I would be happy to provide that. Anything to get this working!

Thank you

**Comment by carolinux** [comment]
I would try to add seconds to the data, ie yyyy/mm/dd hh:MM:SS 
I havent tested the minute only format extensively, so it might be that it doesnt work as expected.
Please send me a small sample at carolinegr@gmail.com if you want me to take a look when i have the time.

**Comment by bschiltz** [comment]
That appears to have solved the problem. I will keep playing to make sure and update later today but it looks good so far. Thank you for the help!

**Comment by bschiltz** [comment]
http://i.imgur.com/KKJX8qR.gif

The plugin appears to be working as expected now. 

Thank you again for the help carolinux!

**Comment by carolinux** [comment]
Excellent. Thanks for sharing the animation too. You know, in QGIS you can use custom symbols so you could potentially have little cow icons running around. ^_^ May I ask if this is a part of a research project? I know the University of Zurich is doing something along those lines.

I once made an animation with aliens.
https://i.imgur.com/1X3eC9R.png

In the meantime, I may remove the minute only format from the supported formats. Nobody had used it so far it seems.

**Comment by bschiltz** [comment]
Ha, that would be great! I'll have to look into making up some cow icons :)

Yes, this is part of a research project at the University of Nebraska. We are looking at cow herd dynamics and trying to discover what environmental factors (vegetation, slope/elevation, distance to water, etc.) are driving movement throughout a pasture. My boss did some similar work in New Mexico for his PhD investigating spatial memory of cows and seeing how often they returned to specific areas with supplemental feed. Previously linear regression or multiple regression was the primary analysis method for this data, along with some limited use of heat maps for visualization. I think Time Manager presents a huge opportunity to better visualize the temporal aspect of this data and may lead to some new observations.

Do you or Anita have a preferred citation for giving credit in papers/presentations?

**Comment by carolinux** [comment]
Tagging @anitagraser for her to weigh in.
I think putting a link to the Time Manager github and our names (Anita Graser and Karolina Alexiou)
would be enough.

**Comment by anitagraser** [comment]
I have an older paper that is citable (in German):
Graser, A. (2011). Visualisierung raum-zeitlicher Daten in Geoinformationssystemen am Beispiel von Quantum GIS mit „Time Manager“-Plug-In. In Proceedings of FOSSGIS2011, Heidelberg, Germany. ISBN: 978-3-00-034124-3; S. 73 – 75.

... Will have to write something new eventually I guess :-)

**Comment by bschiltz** [comment]
Wonderful, thank you both again!

**Comment by bschiltz** [comment]
After some more testing and playing with simple files, I think the problem was not the 'hh:MM' time format, but something funky with how the .csv was being exported. I exported the file from Excel as a .csv and I think it was truncating zeros off the month and hour values. I went back and used "Format Cells -> Custon" to define the "yyyy/mm/dd HH:MM" format and that seemed to work just fine. Darn you Microsoft!

**Comment by carolinux** [comment]
sounds like the most likely cause. Thanks for reporting back.

**Comment by jejevan** [comment]
hi.. i have also the same problem.. no points show up =( i am using mysql.

![x2](https://cloud.githubusercontent.com/assets/25928767/23166245/d2ec8960-f87a-11e6-9e35-a1fdbfac0308.png)
![x3](https://cloud.githubusercontent.com/assets/25928767/23166246/d2f18d02-f87a-11e6-9439-f26c060a1476.png)
![x1](https://cloud.githubusercontent.com/assets/25928767/23166247/d2f44736-f87a-11e6-9049-e66376b83192.png)

=( pls help.
