### ISSUE TITLE
Interpolated layers should be able to copy any parent layer style

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#156]
Currently the creation of the interpolated layer fails if the parent layer uses anything more complicated than a single symbol renderer. 

I'd suggest to simply copy the parent layer's style. Don't try to change transparency or anything. The user can take care of that.

**Comment by carolinux** [comment]
@anitagraser 
The behavior can be changed here: https://github.com/anitagraser/TimeManager/blob/master/timevectorinterpolatedlayer.py#L52

**Comment by anitagraser** [comment]
This still needs #205 to really work

**Comment by anitagraser** [comment]
Something goes wrong when copying the renderer. The log shows "No renderer for drawing"
