### ISSUE TITLE
Folder for saving animation not remembered

### ISSUE THREAD

**Issue by pcav** [anitagraser/TimeManager#157]
The plugin does not remember last choice.

**Comment by anitagraser** [comment]
This wrapper function should probably be used https://github.com/qgis/pyqgis_wrappers/blob/master/parfait/gui.py#L65

**Comment by carolinux** [comment]
I'm exporting a bunch of videos and this is admittedly slightly irritating. I think I will look into this soon.

**Comment by carolinux** [comment]
045236826ce addresses this
