### ISSUE TITLE
Improve "Could Not Match Value" Error Message

### ISSUE THREAD

**Issue by riggsd** [anitagraser/TimeManager#158]
There's a utility method [`createNiceMessage`](https://github.com/anitagraser/TimeManager/blob/1db8db808e2e504da2735af1cf6c8663b8fc438c/time_util.py#L337) for building a friendly error message when a date format can't be inferred, but that message isn't exactly "nice".

The concatenated list of formats is so long that it scrolls completely off my MacBook's display!

<img width="1440" alt="screenshot 2016-03-28 19 01 58" src="https://cloud.githubusercontent.com/assets/647785/14097181/76d363de-f523-11e5-854c-0eb79ce10283.png">

Perhaps you could at least trim out the dozens and dozens of explicit `generate_all_timezones` formats from this list? Perhaps we can do some input scrubbing and reuse `%z` to cover these two-digit UTC offsets as well?

This error message is the most frequent one seen by new and experienced users of TimeManager; it would aid in usability if it were truly *helpful* to the end user rather than giving a blind dump of machine-generated format strings. How about including A) format string documentation, and B) example datetimes in the default formats... or simply a succinct, friendly message with links to A and B.

**Comment by carolinux** [comment]
Seems like you put some thought to it/ familiarized yourself with the code
-- why dont you make an attempt at a pull request for this?
Στις 29 Μαρ 2016 5:35 ΠΜ, ο χρήστης "David A. Riggs" <
notifications@github.com> έγραψε:

**Comment by carolinux** [comment]
I think the best way to go about this is to have links to the github readme file, which can be more detailed or even have an additional .md file that deals with formats and their examples.

**Comment by carolinux** [comment]
Version 2.2.3 has a trimmed list
