### ISSUE TITLE
wms-t layers with &time=.... parameter do not work (yet?)

### ISSUE THREAD

**Issue by rduivenvoorde** [anitagraser/TimeManager#168]
Reading "Using TimeManager for WMS-T layers" at
http://planet.qgis.org/planet/tag/spatio-temporal%20data/
made me try this out.

I have the example service with the -Karolina- Katrina hurricane working.

But trying out a national wms-t service with precipitation data I can not make it to work...

There is a webviewer which uses the wms-t services:

http://geoservices.knmi.nl/viewer2.0/?srs=EPSG%3A3857&bbox=-725.7203842048766,6500000,1220725.7203842048,7200000&service=http%3A%2F%2Fgeoservices.knmi.nl%2Fcgi-bin%2FRADNL_OPER_R___25PCPRR_L3.cgi%3F&layer=RADNL_OPER_R___25PCPRR_L3_COLOR%24image%2Fpng%24true%24default%241%240&selected=0&dims=time$current&baselayers=streetmap$world_line

So I tried to add that layer via capabilites url:
http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi?

And timestamps like: 2016-06-15T08:40:00Z 

But looking into the url's fired by QGIS (Debug compiled), I do not see the time-dimension added to the url's.
It appears that this service seems only want to have 1 time: &time=2016-06-15T08%3A30%3A00Z
like below:

http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi?SERVICE=WMS&&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS=RADNL_OPER_R___25PCPRR_L3_COLOR&WIDTH=886&HEIGHT=603&CRS=EPSG%3A3857&BBOX=-725.7203842048766,6434348.070664023,1220725.7203842048,7265651.929335977&STYLES=default&FORMAT=image/png&TRANSPARENT=TRUE&&time=2016-06-15T08%3A30%3A00Z

And not a time-frame like the Katrina example.
I tried to have a look into the WMS-provider code of QGIS, but I do not see any mention of time-dimensions there, and wonder how the Katrina one can actually work. 
I see that you add a &TIME=.... to the datasource-uri, but I cannot see what happes after that.

Any idea what I'm doing wrong? Or maybe you can tell me what I have to do to make this work (happy to try this out and do a pull request)

TIA

**Comment by carolinux** [comment]
Hello,
so as you've probably already seen, I do add the time= to the datasource uri in the code here:

https://github.com/anitagraser/TimeManager/blob/master/raster/wmstlayer.py#L59

and then the data is reloaded from the wmst service. So probably the url is not set correctly for this other WMST service, probably because this expects one time and not two as you've deduced.

If you want to work on this/try things out, you can select the layer you have, go to the qgis console and do:
```
layer = iface.activeLayer()
layer.dataProvider().setDataSourceUri(correct_url)
layer.dataProvider().reloadData()
```

I don't know if there's a way to get the type of timequery the wmst layer expects. Perhaps through getCapabilities? I would also try to just change the line here:
https://github.com/anitagraser/TimeManager/blob/master/raster/wmstlayer.py#L59

to not have the endtime ie (for a quick local fix, this will make the katrina wmst not work):
```
self.layer.dataProvider().setDataSourceUri(self.IGNORE_PREFIX + \
                                                   self.originalUri + self.addUrlMark() + "TIME={}" \
                                                   .format(
            time_util.datetime_to_str(startTime, self.timeFormat))
```

**Comment by rduivenvoorde** [comment]
Thanks, C tried that. But the 'time'-component does not show up in the url's that I see requested by QGIS. Though if I ask for the dataSourceUri() in the Python console, they are added.... and changing. But QGIS does not take that part into account when it requests the data.
It IS using it for Katrina data though :-(

**Comment by carolinux** [comment]
strange, could it be that the url is invalid ? what happens if you put it
on the browser? I can look at the relevant qgis code later to see if it
does some filtering to the url...

**Comment by rduivenvoorde** [comment]
Ok, found the crux:

From Katrina:

src/providers/wms/qgswmscapabilities.cpp: 40: (parseUri) [15075ms] uriString = IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&contextualWMSLegend=0&crs=EPSG:4326&dpiMode=7&featureCount=10&format=image/png&layers=nexrad-n0r-wmst&styles=&url=http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?TIME=2005-08-29T06:00:00Z/2005-08-29T07:00:00Z

src/providers/wms/qgswmscapabilities.cpp: 49: (parseUri) [37684ms] mBaseUrl = http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r-t.cgi?TIME=2005-08-29T06:00:00Z/2005-08-29T07:00:00Z&

But from KNMI:

src/providers/wms/qgswmscapabilities.cpp: 40: (parseUri) [40061ms] uriString = IgnoreGetFeatureInfoUrl=1&IgnoreGetMapUrl=1&IgnoreGetMapUrl=1&contextualWMSLegend=0&crs=EPSG:28992&dpiMode=7&featureCount=10&format=image/png&layers=RADNL_OPER_R___25PCPRR_L3_COLOR&styles=&url=http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi?&TIME=2016-06-13T18:00:00Z/2016-06-13T18:01:00Z

src/providers/wms/qgswmscapabilities.cpp: 49: (parseUri) [0ms] mBaseUrl = http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi?

So the parseUri looses the TIME component (be it an interval (as yours, actually also working for knmi) or a single time.. 

The crux seems to be the '&' behind the '?' which is added by addUrlMark of the plugin...
Temporarily removing it from the url (that is returning "" if "?" in originalUri) makes stuff just work:

http://test.duif.net/animation.gif

I'll dive into this to fix it properly and do a pull request

**Comment by carolinux** [comment]
Ok, a general fix would be in this direction:  if the url already has a
question mark, one shouldn't add it again.
