### ISSUE TITLE
Exception Imagemagick is not in path

### ISSUE THREAD

**Issue by tph018** [anitagraser/TimeManager#171]
Hi, 

I am a new user to the TimeManager plugin within QGIS for the MacOS and wish to export an animated gif. However, I obtain the following error, even though I have installed ImageMagick via HomeBrew.

May you please advise how I go about placing ImageMagick in the appropriate path?

-tph018

- - - - - - -
An error has occured while executing Python code:

Traceback (most recent call last):
  File "/Users/tony/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 266, in exportVideo
    animate.make_animation(path, delay_millis)
  File "/Users/tony/.qgis2/python/plugins/timemanager/animation/animate.py", line 40, in make_animation
    raise Exception("Imagemagick is not in path. Please install ImageMagick!")
Exception: Imagemagick is not in path. Please install ImageMagick!

Python version:
2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

QGIS version:
2.8.3-Wien Wien,

**Comment by carolinux** [comment]
You need to be able to run the *convert* command when you open a terminal. 
Look here: http://www.imagemagick.org/script/binary-releases.php
especially the part where it tells you how to add the binary for imagemagick to PATH.

**Comment by tph018** [comment]
Hi carolinux,

I am indeed able to run the convert command in a terminal session. Moreover, I am able to take a collection of images such as those generated by TimeManager and execute in terminal a "convert" command to create an animated gif. 

However, I am not able to appropriately configure the TimeManager plugin within QGIS for the MacOS and to work with ImageMagick as I continue to get the same error message as above when I attempt to export an animated gif via the QGIS TimeManager plugin. So, the bottom line is that I can generate the desired animated gif of the TimeManager's exported png files using ImageMagick within command line but I cannot do the same using the TimeManager plugin's "Export Video -> Animated gif" feature.

Perhaps you have other thoughts?

-tph018

**Comment by carolinux** [comment]
see if the command : 
convert -version
returns a non-zero exit code. What version of image magick do you have?

**Comment by tph018** [comment]
Upon running "convert -version", I obtain a non-zero exit code (with the version of ImageMagick provided):

"
Version: ImageMagick 6.9.4-9 Q16 x86_64 2016-06-21 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib fontconfig freetype jng jpeg ltdl lzma png tiff x xml zlib
"

**Comment by carolinux** [comment]
Ok, that's weird that imagemagick does that. As a short term solution- try to get a different version - I have  6.7.7-10 of imagemagick and it works.

**Comment by tph018** [comment]
I'll go ahead and close the issue for now. I have elected to continue using ImageMagick 6.9.4-9 and will simply use ImageMagick outside of TimeManager altogether to generate the desired animated gif rather than using TimeManager to call upon ImageMagick for the desired output. 

Nonetheless, I love the TimeManager plugin and am appreciative of the work effort and continued support of the product!

**Comment by puntofisso** [comment]
For the record, this is still happening and the cause is the fact that the system path is not defined in  QGIS as it is on the system. ImageMagick is installed under /usr/local/bin, which is in my system terminal's path
bash-3.2$ echo $PATH
`/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/puntofisso/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

but not in the QGIS python console
`>>>os.environ["PATH"]
'/usr/bin:/bin:/usr/sbin:/sbin'`

I'm not expert enough about QGIS to understand if you can set the path specifically (I'm looking around and will comment if necessary). However, a quick workaround is to actually add the path via the Python Console and then use TimeManager:
```
>>>os.environ["PATH"] += os.pathsep + "/usr/local/bin/"
>>>os.environ["PATH"]
'/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/'
>>>subprocess.check_call(["convert", "-version"])
0
```.
