### ISSUE TITLE
remove *.PNGw files with "Clear previous frame files in directory" option or rename option

### ISSUE THREAD

**Issue by elil** [anitagraser/TimeManager#172]
Awesome plugin!  Thanks.  

During exports with the "Clear previous frame files in directory" option selected, *.PNGw files remain (if the number of frames of the current export is fewer than the previous export).  

I would expect these *.PNGw files to be gone with this option selected.  Some regex like rm frame*.PNGw might work for that.  However, erring on the side of caution of accidentally deleting user files would make that a bad idea.  In that case, perhaps the option could be renamed some thing like "Overwrite previous frame files in directory" (which appears to be what it is maybe doing).  

Or that could just be my commentary and it is best as is.  Either way, a great tool!

Ubuntu 14.04, QGIS 2.14.3, TimeManager 2.2.4

**Comment by carolinux** [comment]
Small fix, done.
