### ISSUE TITLE
Postgis Datetime column results in wrong query?

### ISSUE THREAD

**Issue by rduivenvoorde** [anitagraser/TimeManager#180]
Hi,
I have data with one DateTime column in Postgis, it is the last column called 'bouwdate':

![selection_033](https://cloud.githubusercontent.com/assets/731673/16517024/966de906-3f7b-11e6-8a73-a8cddce3dace.png)

If I use time manager with that layer and use 'bouwdate' as start column, the timeformat is determined correctly, but never shows records.
Looking at the filter-query, it results in a query like for example:

cast("bouwdate" as character) < '1984-01-01T01:00:00' AND cast("bouwdate" as character) >= '1983-01-01T01:00:00'

Which if I run:

select * from thistable where
cast("bouwdate" as character) < '1984-01-01T01:00:00' 
AND 
cast("bouwdate" as character) >= '1983-01-01T01:00:00'

always return 0 records.
Without the AND clause and taking one of the cast-parts both return valid number of records.
But... a bouwdate is never both < a date AND > a date (stringcomparing)...

So this will never work? Unless I think we do a proper time-filter, though not sure if QGIS/OGR has that?

**Comment by carolinux** [comment]
Not sure I understood why this query doesnt work:
```
cast("bouwdate" as character) < '1984-01-01T01:00:00' AND cast("bouwdate" as character) >= '1983-01-01T01:00:00'
```
wouldn't 1983-01-01T01:00:00 be returned for this? 
In general the standards for OGR comparisons are conflicting and the way it is now works at least for a majority of cases.

**Comment by rduivenvoorde** [comment]
Mmm, testing the cast here:
after showing:  
that 
select cast("bouwdate" as character) from table
only results  in 1 char like: '1' or '2' ??

select cast ('1983-01-01' as character) from table 
results in '1' only...
Instead of the '1983-01-01' ... ?

**Comment by carolinux** [comment]
what is the string for
layer.dataProvider().type() 
I think this has been reported before here: https://github.com/anitagraser/TimeManager/issues/159
So closing this one.
