### ISSUE TITLE
Removing casts make postgis queries times faster

### ISSUE THREAD

**Issue by nextstopsun** [anitagraser/TimeManager#187]
I was looking at an issue with `Provider filter` query casting field values to `character` type for postgis layers. As discussed in other issues, this cast causes `QDateTime` field transform into just first character of the string, which ends up with empty table in result. I didn't want any casts, because my postgis table is really huge and properly indexed by `timestamp` field and then clustered on this index. So queries are relatively fast in the DB, but not fast at all with those casts.
So I've edited `query_builder.py` and added this:

```
# STRINGCAST_FORMAT = 'cast("{}" as character) {} \'{}\' AND cast("{}" as character) >= \'{}\' '
STRINGCAST_FORMAT = '{} {} \'{}\' AND {} >= \'{}\'
```

Fortunately this works (that `T` letter doesn't seem like a problem for postgres) and I'm quite sure my index is used when data updates on every frame.
This looks like a dirty hack, but maybe could be improved, so that layers with postgis data source can use uncasted variant of this filter. Done that with postgres 9.5, unsure if it works for older versions.

**Comment by rduivenvoorde** [comment]
@nextstopsun  plz also have a #159 the STRINGCAST_FORMAT is not only used for postgres but for all OGR datasources I think. Best if you try to do a pull request and see if it passes all tests maybe?

**Comment by nextstopsun** [comment]
@rduivenvoorde Yes, I meant that discussion. I'm almost sure this PR would fail because it's just a hack, not a fix. I understand that this cast is for generic OGR datasources, my opinion is that STRINGCAST_FORMAT string should be generated for each layer separately depending on the contents of `mDataSource` property. But the logic is to use `QueryIdioms` that I don't quite get. I suspect, that [this check](https://github.com/anitagraser/TimeManager/blob/master/query_builder.py#L165) ends up being true for postgis, so simple `STRING_FORMAT` is never used. This check needs to be changed, but I don't know the best way to figure out datasource type. Any thoughts?

Generally, the contents of `query_builder.py` are a bit more complicated than what I expected:) I thought it should contain just a tiny wrapper around the initial provider filter, something like `({initial provider filter} AND {time frame conditions})` if it's applicable for a certain layer type.

**Comment by carolinux** [comment]
@nextstopsun The query builder module has been built to support a lot of special cases (but in a way where new cases were added in gradually, as opposed to designing it from the beginning). I think a simplification along the lines you propose is possible, but I am short on time. This issue and #159 are all related to this.

**Comment by carolinux** [comment]
hmm a work around to alleviate part of this pain and suffering quickly could be to have an option to check that "yes I have postgresql dates as my datatype" and then use the query without the cast when this is checked. what do you think @anitagraser  ?

**Comment by anitagraser** [comment]
I'm ok with that. Could it be implemented in a way, that the checkbox is only available if the selected layer is a PostGIS layer?
