### ISSUE TITLE
Use of QTimer.singleShot creates parallel render/provider processes

### ISSUE THREAD

**Issue by rduivenvoorde** [anitagraser/TimeManager#188]
When you add a WMTS layer, for example one from here:

http://geoservices.knmi.nl/cgi-bin/RADNL_OPER_R___25PCPRR_L3.cgi?
take one of the two layers (which have 5 minute timeframes):
use as start for example: 
2016-03-30T10:00:00Z
and endstime
2016-03-30T14:00:00Z
timeframe 5 minutes
showframetime 2000 msecs

Now if you start 'playing/animation' all seems fine, BUT when you pull the slider to another 'currentTime', (or via the textinput), timemanager starts apparently two different 'processes', in which on the end of a rendering (wmst-image retrieval) starts a new image retrieval...
So instead of 2000 ms shows, you see two different (faster) timings. The slider also starts to move twice as fast. 
And if you pull the slider another time, you can even have 3 or 4 timers running....

I think it is related to #167 and will provide a patch

**Comment by carolinux** [comment]
should be fixed now
