### ISSUE TITLE
sorting of frames wrong for animation?

### ISSUE THREAD

**Issue by rduivenvoorde** [anitagraser/TimeManager#198]
Having hourly data for 12 hours, if I run an animation and looked at it, I mentioned a strange ordering in time (hours).

Looking int the debug info this is shown:

Exported 12 frames to gif /tmp/1558/animation.gif (call :['convert', '-delay', '1x1', u'/tmp/1558/frame0.png', u'/tmp/1558/frame1.png', u'/tmp/1558/frame10.png', u'/tmp/1558/frame11.png', u'/tmp/1558/frame2.png', u'/tmp/1558/frame3.png', u'/tmp/1558/frame4.png', u'/tmp/1558/frame5.png', u'/tmp/1558/frame6.png', u'/tmp/1558/frame7.png', u'/tmp/1558/frame8.png', u'/tmp/1558/frame9.png', u'/tmp/1558/animation.gif'])

If I'm correct the sorting on the framenames is not right?
0, 1, 10, 11, 2, 3 ...

Sorting is done here:
https://github.com/anitagraser/TimeManager/blob/master/animation/animate.py#L47

This would work if we use 'leading zero's'?
Though this would also force us to know the final number of frames (to know the 'width' of the number)?

Did nobody have this problem yet?

**Comment by rduivenvoorde** [comment]
Yes, just found out those line :-)

I will try to reproduce it and either sent you data, or fix it.

**Comment by rduivenvoorde** [comment]
[10hour.zip](https://github.com/anitagraser/TimeManager/files/481826/10hour.zip)
This is a cornercase zip with 10 timeframes (choose 'time' as parameter).

Looks indeed like we are 'off by one'.. 

Not sure how I could end up with 12 frames and the same problem though.

I will fix that anyway, but we could also just add an extra zero  by adding +1 here

https://github.com/anitagraser/TimeManager/blob/f8fb07218a9f0e577c6095ce1d6ac2ff98566d5d/timemanagercontrol.py#L286

I'm thinking about other border/corner cases like leap years etc in which it is easy to get an off by one.

Ok?

**Comment by carolinux** [comment]
Ok, and add a comment that this is quick fix and reference #198

**Comment by carolinux** [comment]
@rduivenvoorde  fixed it for now
