### ISSUE TITLE
Implement on-the-fly interpolated frames

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#2]
Add functionality to create "tracer" frames on-the-fly. 

 Needs interpolation between two successive timestamps and creation of a new (in-memory?) layer. 

 Goal: Nicer animations, easier to follow moving objects.

**Comment by carolinux** [comment]
working on it in branch interpolation

**Comment by carolinux** [comment]
already have some beta testers for interpolation. Let's close this and open issues for individual stuff that arises.
