### ISSUE TITLE
Doubled frames

### ISSUE THREAD

**Issue by Kubwal** [anitagraser/TimeManager#200]
Hello,

We have been testing the TimeManager Plugin for QGIS trying to find an efficient way to animate METEOSAT imagery imported from EUMETView MWS Server and integrated with other geospatial data.
We have the following problem: while exporting frames some of them are doubled whereas time display is changed.
Any ideas what may be a cause and how to deal with it?

Cheers!
Jakub

**Comment by carolinux** [comment]
this should be fixed in Time Manager 2.3.1 
Please let us know if this is or is not the case
