### ISSUE TITLE
WMS-T Format: not adding time in the url correctly

### ISSUE THREAD

**Issue by Chackadar** [anitagraser/TimeManager#202]
Hello,

I am having trouble getting the TM plugin to work. I am using QGIS 2.16.2 and TM 2.3 I have tried searching for answers all over the web but found nothing.

I have data that I want to animate with TM.  First step : I load directly my .csv in QGIS and do the animation with TM.  Everything work as expected.

Second step : I have put the data in a pg database using ogr2ogr.  Then I imported the data from the db to QGIS and try the animation.  Everything work as expected.

Third step : I have created a mapfile to expose my data with a mapserver in WFS format.  Once again, I put that in the TM plugin and every thing work as expected.

Last step, the problem begin.  Using usige the same mapfile, I want to espose my data using a wms-t service.  When I open my wms-t in a web browser using something like
http://192.168.54.88/cgi-bin/mapserv?version=1.3.0&service=WMS&request=GetMap&sld_version=1.1.0&map=mes.map&layers=vent_barbule_time_data_p&CRS=EPSG:4326&EPSG:4326&BBOX=-90.0,-90.0,90,90.0&WIDTH=2048&HEIGHT=2048&format=image/png&time=2015-08-05 09:00:00
I have my data at the timestamp 2015-08-05 09:00:00.  Everything work as expected.
If I open my wms-t in QGIS, it show (as expected?) all my data.  If I want to use TM, it alwais show all the data, no matter witch timespamt I use or where is the annimation.  If I look at my appache log access.log, the request is always 
"GET /cgi-bin/mapserv?map=mes.map&&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&BBOX=-77.00332207207208057,43.35377252252252589,-64.53457207207208057,48.52100225225225216&SRS=EPSG:4326&WIDTH=1665&HEIGHT=691&LAYERS=vent_barbule_time_data_p&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE HTTP/1.1" 200 304895 "time" "Mozilla/5.0 QGIS/2.16.2"
Isnt' it supposed to use something like &time=something?

What I want is to animate my wms-t using diferent timestamp.  What I got is always all the data no matter what is the time stamp.  Am I doing something wrong?  Is it a TM problem?  How to have what I want?

My mapfile is looking something like 

MAP
# CONFIG "MS_ERRORFILE" "/var/www/ms_tmp/ms_error.txt"
# CONFIG "CPL_DEBUG" "ON"
# CONFIG "PROJ_DEBUG" "ON"
# DEBUG 5

```
NAME "mesonet"
STATUS ON
SIZE 800 800
SYMBOLSET "./include/symbols.txt"
PROJECTION
  "init=epsg:4326"
END
EXTENT -145 40 -50 75
UNITS METERS
SHAPEPATH "/usr/lib/cgi-bin/data/"
IMAGECOLOR 255 255 255
FONTSET "./include/fonts.txt"

WEB
  IMAGEPATH "/tmp/ms_tmp/"
  IMAGEURL  "/ms_tmp/"
  METADATA
    "wfs_title"           "mesonet"
    "wfs_onlineresource"  "http://192.168.54.88/cgi-bin/mapserv?map=mes.map&"
    "wfs_srs"             "EPSG:4326"
    "wfs_abstract"        "Serveur WFS de solution mesonet"
    "wfs_enable_request"  "*"
    "wms_title"           "mesonet"
    "wms_onlineresource"  "http://192.168.54.88/cgi-bin/mapserv?map=mes.map&"
    "wms_srs"             "EPSG:4326"
    "wms_abstract"        "Serveur WMS de solution mesonet"
    "wms_enable_request"  "*"
  END
  TEMPLATE "./include/template.html"
END

LAYER
  NAME "vent_barbule_time_data_p"
  STATUS ON
  TYPE POINT
  INCLUDE "./include/connection_mesonet.map"
  DATA "geom_p from mes_v_barbule_time_data_p using unique key using srid=4326"
  PROJECTION
    "init=epsg:4326"
  END

  METADATA
   "wfs_title"          "vent_barbule_time_data_p"
   "wfs_layer_group"    "/mes/"
   "wfs_srs"            "EPSG:4326"
   "gml_include_items"  "all"
   "gml_featureid"      "key"
   "wfs_enable_request" "*"
   "wms_title"          "vent_barbule_time_data_p"
   "wms_layer_group"    "/mes/"
   "wms_extent"         "-145 40 -50 75"
   "wms_timeextent"     "2015-08-05/2015-08-06"
   "wms_timeitem"       "date"
   "wms_timedefault"    "2015-08-05 06:00:00"
  END

  TEMPLATE "./include/template.html"

  CLASS
    NAME "< 0 KM/H "
    EXPRESSION ([vvm425h] < 0)
    STYLE
      SYMBOL "barbule_8"
      COLOR 255 255 0
      OUTLINECOLOR 0 0 0
      SIZE 72
      ANGLE [vdm425h]
    END
  END

  CLASS
    NAME "[0 - 2.5] KM/H"
    EXPRESSION (([vvm425h] >= 0) && ([vvm425h] <= 2.5))
    STYLE
      SYMBOL "barbule_9"
      COLOR 255 255 0
      OUTLINECOLOR 0 0 0
      SIZE 72
      ANGLE [vdm425h]
    END
  END
  ...
  CLASS
    NAME "> 147.5 KM/H"
    EXPRESSION ([vvm425h] > 147.5)
    STYLE
      SYMBOL "barbule_3"
      COLOR 255 255 0
      OUTLINECOLOR 0 0 0
      SIZE 72
      ANGLE [vdm425h]
    END
  END
END
```

END

**Comment by carolinux** [comment]
The WMS-T feature was experimental. Time Manager does not claim to support the full range of the WMS-T format.

**Comment by carolinux** [comment]
If you want to debug your particular case, you can look at what url is generated by Time Manager in this line by adding a break point here:
https://github.com/anitagraser/TimeManager/blob/master/raster/wmstlayer.py#L63

I am thinking perhaps the url generated by Time Manager in this case is not correct so it doesn't get updated.

**Comment by rduivenvoorde** [comment]
@Chackadar can you show us how you configured the raster layer in timemanager?
Did it not give you errors?
If you provide some data, I can try to set up mapserver here locally with that?

One thing I noticed is that a WMSTRasterLayer currently needs both a start and an end time (which is good, because timemanager needs to know the initial time-range of the timeslider. But it would be cool to be able to request MapImages without a range. What I mean: now we always add something like: 
&TIME=2016-10-11T10:05:00Z/2016-10-11T10:10:00Z 
meaning a range.
But it would be cool to also be able to request one timestep, so only
&TIME=2016-10-11T10:05:00Z

Mmm, I see there are actually even more possibilities possible in WMS-T:
http://mapserver.org/ogc/wms_time.html#supported-time-requests
while mapserver 
http://mapserver.org/ogc/wms_time.html#specifying-time-extents
is pretty picky in what works and not...

**Comment by anitagraser** [comment]
I have one WMS server connection (to Geoserver) configured to always use VERSION=1.1.1, so the server url is <server>?VERSION=1.1.1& 
Layers added with this configuration are not handled correctly and only show the default map. Without specifying the version explicitly, everything works fine. Still have to debug where the problem sneaks in.

**Comment by anitagraser** [comment]
Should be fixed in https://github.com/anitagraser/TimeManager/commit/f5a6a398e308a994ecec67a006399d0c55d399e9
