### ISSUE TITLE
TimeManager plugin install issues

### ISSUE THREAD

**Issue by rob-burgess** [anitagraser/TimeManager#212]
Hi, I'm trying to install the TimeManager plugin (version 2.3.1) via the QGIS plugins repository. However, on install I get the following error `"The plugin is broken. Python said: No module named six"` (see attached screenshot). I am running QGIS version 2.18.1 32-bit, on Win 7. Just wondering if anyone else has seen this?

![image](https://cloud.githubusercontent.com/assets/7769451/21224262/31d4315a-c2c3-11e6-8512-67d01451d03f.png)

**Comment by carolinux** [comment]
I also got an error "no module named QGis" at some point, but I think it has to do with my QGIS installation being kinda broken at the moment..

**Comment by anitagraser** [comment]
Closed for lack of feedback.
