### ISSUE TITLE
Random sorting of raster layers in selection dialogue

### ISSUE THREAD

**Issue by EdRollason** [anitagraser/TimeManager#213]
When you're selecting rasters (not checked with vector data) the selection dropdown appears to be randomly sorted, making it difficult to work out what to select.  

My files are named "YYYY-MM-DD hh:mm:ss" and the QGIS TOC orders them ok but when I open the selection window in Time Manager it doesn't match the TOC order.  You can see the behaviour in the attached screenshot.

QGIS version: 2.16.2 (on Mac OS installed from Kyngchaos)
Time Manager version: 2.3.1

<img width="1361" alt="select_layer_and_column_s__and_time_manager_settings_and_qgis_2_16_2" src="https://cloud.githubusercontent.com/assets/7903405/21853315/8566ab08-d80e-11e6-971c-8451f15c0077.png">

**Comment by carolinux** [comment]
@EdRollason see if this new branch fixes your problem, and I will make this fix ship with the next version of TimeManager

**Comment by anitagraser** [comment]
Closing for lack of feedback. Reopen if necessary.
