### ISSUE TITLE
QGIS 3.0 discussion

### ISSUE THREAD

**Issue by nyalldawson** [anitagraser/TimeManager#221]
Hey Time Manager team,

I'd like to raise some discussion on ways to improve time manager based on api improvements and new features available in qgis 3.0. Is this the best place for this?

You may have seen some demo videos like this https://www.youtube.com/watch?v=2jsYRxmnWkI floating around - I think it'd be really neat to be able to take advantage of both the new symbology features and also the inbuilt canvas autorefresh with Time Manager.

**Comment by anitagraser** [comment]
Hi Nyall, this is definitely the right place!
I've already been wondering what is going on in the background of this video.
Would be great if you could provide us with insights into the new API features.

**Comment by nyalldawson** [comment]
Ok, so first up: the video isn't really an animated map as such. It's using the new "epoch" function to calculate the number of milliseconds since a time stamp in the features, and then plugging this into the data defined overrides.

It then uses a new feature for auto refreshing layers, set to refresh the layer 20 times a second. That's what gives the animated appearance. But in reality these are still just static points, it's just the symbol which is changing.

So there's a few things I'd like to discuss here. One is whether this canvas/layer auto refresh could be useful for time manager. 

I'd also like to explore whether time manager outputs could be made outside of the map canvas, such as in a background task. 

Lastly.. that video shows off some new assistants for styling layer colors and other properties. When I was designing this system animated maps were very much in my mind. It should be possible to extend this so that the assistant could use time based values for the property source.

Eg:
- start animation "x" frames before feature start time
- end animation "x" days/weeks/months after feature end time

Most of the framework for this kind of thing is now in place, but I want to make sure we get all the API required for time manager to be able to utilise this before 3.0 is finalised.

**Comment by anitagraser** [comment]
Great! Currently, as you probably know, we rely on provider filter queries to filter out features that are not within a certain time window. In my experience, with big datasets, it is unfeasible / slow to rely on (rule-based) styling alone to render only the desired features. So we probably need to keep the provider filters. 

As you probably know, TimeManager exposes its current animation_datetime() and we've been using similar approaches to what you described using epoch to create "fading" effects. Writing the data-defined expressions to use animation_datetime() is quite painful though and not very user friendly.

**Comment by cz172638** [comment]
hi,
any update on qgis3 and time manager?

**Comment by anitagraser** [comment]
@cz172638 I'll probably attempt porting when 3.0 is released at the end of February (https://qgis.org/en/site/getinvolved/development/roadmap.html). We'll see how difficult it is.

**Comment by ranaalisaeed** [comment]
Hi Time Manager team,
Any update on qgis3 and time manager? 3.0 is released and I'm really looking forward to being able to work with time manager again.

**Comment by anitagraser** [comment]
There is no definite time schedule yet. Any contributor who wants to give it a try is welcome to port it.

**Comment by anitagraser** [comment]
The first version for QGIS 3 has now been published.

**Comment by anitagraser** [comment]
@nyalldawson I've created separate tickets for the ideas you outlined above
