### ISSUE TITLE
Trouble with including both start and end times

### ISSUE THREAD

**Issue by mikitonez** [anitagraser/TimeManager#223]
Hi there,
I'm totally new to QGIS, just muddling along trying to make a map of weather reporting stations in the U.S. during the 19th century for a historical research project. Some of these stations were short-lived, so I want the map to show when they appear and have the points disappear when they closed (and my data has columns for when the stations opened and closed in YYYY-MM-DD format.) TimeManager seems like the way to do this, but I can't get my data layer accepted when I include both the start time and the end time. I get the following error message: "An error occured while trying to add layer shapefile stations to TimeManager. Cause: UnsupportedFormatException('Could not find a suitable time format for value NA',)"
TimeManager does accept my layer when I make the end time the same as the start time, but this isn't quite what I want the animation to show. Does anyone have thoughts on how I might resolve this? It's very possible that I am making a newbie mistake because I don't understand QGIS or coding language very well.
I'd be so very grateful for any tips you can give me!

**Comment by carolinux** [comment]
Hi there,
You probably have some end times in your data, that instead of a date, are
the string "NA". Replace those with a valid date. Can be also a date in the
far future.

Στις Κυρ, 19 Μαρ 2017 - 17:50 ο χρήστης mikitonez <notifications@github.com>
έγραψε:

**Comment by mikitonez** [comment]
It worked!!! Oh my goodness, thank you so very much. And thank you for all your hard work on this awesome plug-in!
