### ISSUE TITLE
Animate based on alphanumerical fields?

### ISSUE THREAD

**Issue by charleyglynn** [anitagraser/TimeManager#226]
I love this plugin and have been using it a lot recently. 

As the name is TIME Manager, this request might seem a bit ironic.

Would it be possible to create an animation based on ANY attribute field (in ascending or descending order) e.g. a numerical sequence 1,2,3,4,5,6,7,8,9,10 etc. or even a text string in alphabetical order like A,B,C,D,E,F,G etc.

**Comment by anitagraser** [comment]
A simple numerical sequence should already work. Have you tried it?

**Comment by charleyglynn** [comment]
I have but I will try again - there may have been another reason that it didn't work.
Any plans to add alphabetical ordering of text strings?

**Comment by charleyglynn** [comment]
OK cool, I got a numerical sequence (it was an Eastings column) working. Thanks.

**Comment by anitagraser** [comment]
Closing as "wont fix".
