### ISSUE TITLE
Add support for microseconds

### ISSUE THREAD

**Issue by DrPoldo** [anitagraser/TimeManager#228]
I' m currently using TimeManager 2.3.2 with QGis 2.18.6 on Windows 10.
To reproduce this issue time format must have microseconds and "accumulate feature" must be flagged.
With these condition the following exception is returned:

> Exception in function "refreshTimeRestrictions" invalid string format

I've catched the exception and this is the stacktrace:

> 2017-04-21T17:07:55	0	Traceback (most recent call last):
			  File ".../.qgis2/python/plugins\timemanager\timelayermanager.py", line 118, in refreshTimeRestrictions
			    timeLayer.setTimeRestriction(self.getCurrentTimePosition(), self.timeFrame())
			  File ".../.qgis2/python/plugins\timemanager\timevectorlayer.py", line 242, in setTimeRestriction
			    acc=self.accumulateFeatures()
			  File ".../.qgis2/python/plugins\timemanager\query_builder.py", line 157, in build_query
			    start_str = time_util.datetime_to_str(start_dt, date_format)
			  File ".../.qgis2/python/plugins\timemanager\time_util.py", line 258, in datetime_to_str
			    return _fixed_strftime(dt, fmt)
			  File ".../.qgis2/python/plugins\timemanager\time_util.py", line 294, in _fixed_strftime
			    s1 = time.strftime(fmt, (year,) + timetuple[1:])
			ValueError: Invalid format string

The problem is that **time.strftime** doesn't support microsenconds, probably **datetime.strftime** should be used but i'm new to python so I've just changed *_fixed_strftime* getting rid of ".%f" in the format string. 

```python
def _fixed_strftime(dt, fmt):
    illegal_formatting = _illegal_formatting.search(fmt)
    if illegal_formatting:
        raise TypeError(
            "strftime of dates before 1900 does not handle" + illegal_formatting.group(0))
    year = dt.year
    # For every non-leap year century, advance by
    # 6 years to get into the 28-year repeat cycle
    delta = 2000 - year
    off = 6 * (delta // 100 + delta // 400)
    year = year + off
    # Move to around the year 2000
    year = year + ((2000 - year) // 28) * 28
    timetuple = dt.timetuple()

    if fmt.endswith('.%f'):     #  <--- that's my code
        fmt = fmt[:-3]

    s1 = time.strftime(fmt, (year,) + timetuple[1:])
    sites1 = _findall(s1, str(year))
    s2 = time.strftime(fmt, (year + 28,) + timetuple[1:])
    sites2 = _findall(s2, str(year + 28))
    sites = []
    for site in sites1:
        if site in sites2:
            sites.append(site)
    s = s1
    syear = "%04d" % (dt.year,)
    for site in sites:
        s = s[:site] + syear + s[site + 4:]
    return s
```
With these changes the plugin works correctly with my current configuration.

**Comment by anitagraser** [comment]
Should be fixed with the port to Python 3. Please reopen if necessary.
