### ISSUE TITLE
Export dialog is not resizing correctly

### ISSUE THREAD

**Issue by SrNetoChan** [anitagraser/TimeManager#230]
The export Dialog seems cropped and it's not resizing correctly

![image](https://cloud.githubusercontent.com/assets/3607161/25629710/6ba8b1e2-2f62-11e7-87b2-b05e3f435dad.png)

**Comment by anitagraser** [comment]
Should be fixed in https://github.com/anitagraser/TimeManager/commit/2fa9336afab0b2f04b56f1cd39e7e6b8fe133f26. Can you check the current master from Github? I still need to publish the new version later this week.

**Comment by SrNetoChan** [comment]
Actually, after I submitted the issue, I cloned the repo to see if I could fix it. And didn't saw the problem there.

Thanks!
