### ISSUE TITLE
interpolated points disappearing during animation

### ISSUE THREAD

**Issue by jess-pmca** [anitagraser/TimeManager#231]
I am attempting to animate gps/geolocator data for bird path migration. The issue I am having during playback is that the linear interpolated points disappear at random times. The path tracks along and without reason the point will randomly disappear only to reappear in a flash a moment later. This causes the scene to hiccup. I have experimented with time settings and that does not seem to help. I do not notice anything unusual in the attributes from points that work smoothly to those that experience the blip. Any idea what I am doing wring? I am a new user, so any help would be greatly appreciated. Many thanks for all you do to help out others.

**Comment by anitagraser** [comment]
Can you share data and settings to reproduce the issue?

**Comment by jess-pmca** [comment]
Thanks for the reply. Sorry for the slow response, we are a very small group and I have been out of the office.

These data are from gps/geolocator packs that were worn by migrating song birds. The goal is to visualize the migration routes of 30+ birds simultaneously.

I imported the original tables into ArcMap, cleaned up the files and created a point shapefile for each songbird.
Then I discovered QGIS. I added all 30+ bird point files to a project, turned on google earth for background, and added the TimeManager plugin to the project.

I added the timestamp field to the attribute table of each bird. I switched the dates in this field to year 2000. This way the migrations from all years would play at the same time.

In TimeManager,  I added a layer.  Each layer is named by the ID given to the bird.
Start time: timestamp
End time: same as start
Linear interpolation (pt. geometries)
ID attribute: none

show frame for 500 milliseconds
frame size 1 days

I have played around with the time settings, but this is where I last encountered the problem. Using the attached sample examples I found that they all together disappear specifically on Jan-07, Jan-14, Jan-21, Jan-28 and one layer (bird) disappears on Jan-10, Jan-17, etc. This goes on and on throughout the sequence.

It looks like my disappearances occur along a weekly pattern. I'm not sure what I may be doing wrong.

This is an amazing plugin, the interpolation does exactly what we were looking for, I just need to learn to use it properly. Thanks for any advice you may be able to give, take care!

________________________________

**Comment by anitagraser** [comment]
I think the sample data did not make it. Can you make it available for download?

**Comment by jess-pmca** [comment]
Sorry about that, I was responding through email, not actual Github.






[birds.zip](https://github.com/anitagraser/TimeManager/files/1148368/birds.zip)

**Comment by anitagraser** [comment]
Thanks! I cannot reproduce the issues here not on the days you mentioned nor on any others
. If you can record a screencast (e.g. using https://screencast-o-matic.com) that could shed more light on the issue.

Here's the test project I configured using your data:
[birds.zip](https://github.com/anitagraser/TimeManager/files/1150351/birds.zip)

**Comment by jess-pmca** [comment]
Fridays seem to be the only day I can get to GIS work, thanks for your kind help and patience. Attched is a short screencast of what I see happening.
[timemanageBIRDs.zip](https://github.com/anitagraser/TimeManager/files/1166489/timemanageBIRDs.zip)

**Comment by anitagraser** [comment]
It seems like you have deactivated the original 4 layers. The points you are missing are the original points. Turn them on and your issue should be solved.

**Comment by jess-pmca** [comment]
Oh my, I feel rather foolish, of course that is the case. I have MUCH to learn. 😊
I am tremendously grateful for your help, sorry to have taken so much of your time.
________________________________
