### ISSUE TITLE
Specify start and end of the timeline animation independently of the features being animated

### ISSUE THREAD

**Issue by CoryAlbrecht** [anitagraser/TimeManager#237]
Currently the time manager just runs from the earliest start point to the latest end point and you cannot stop it in the middle of a render for GIF if movie without an error. But one might want to break up the animation into segments due to either file size or length of time, or one might want to make multiple "chapters" from the same set of data.

For example, one might have a timeline of the territorial evolution of North America since European colonization until today but might want break it down by centuries or by major events.

**Comment by anitagraser** [comment]
Dupliates #107
