### ISSUE TITLE
Changing style on accumulated features

### ISSUE THREAD

**Issue by jbants** [anitagraser/TimeManager#241]
I'm looking to change the style of accumulated features so that features that are X frames behind the current frame have an increased transparency. This will create an animated tail effect. Could someone point me in the right direction for where to make these changes in the code? Thanks!

**Comment by anitagraser** [comment]
In my opinion, time-aware styles shouldn't be the responsibility of TimeManager. There are so many options that it is impossible to cover them all. It would just bloat the plugin code. 

Instead, I recommend creating and sharing time-aware styles using the QGIS resource sharing platform.

**Comment by jbants** [comment]
hmm, time aware styles are interesting. I'll have to look at those more.
Thanks!
