### ISSUE TITLE
About the performance for visualizing real time points

### ISSUE THREAD

**Issue by cyang-kth** [anitagraser/TimeManager#243]
Thank you for this great work. I have a question regarding the performance of visualizing point layers. 

I have a point layer with about 60,000 GPS observations in two hour period with an average interval of 3 seconds. When I run the time manager with 3-second frame update interval (2400 frames), it periodically updates the map and export png files. However, it still takes about half an hour. Is there a way to speed up the process?

**Comment by tjukanovt** [comment]
What format are you currently using for your GPS points? If you are now using a shapefile or even csv, you should try saving them to PostGIS database or even into a geopackage file. That should speed up reading the file significantly.

**Comment by cyang-kth** [comment]
I have tried CSV and Shapefile format, but there is no significant change. I will try the other two later. Which one is faster, PostGIS or Geopackage?

**Comment by tjukanovt** [comment]
Use PostGIS if you have the possibility, but saving it to a Geopackage in QGIS GUI  is simpler and handling 60 000 points pretty fast won't be an issue.
