### ISSUE TITLE
Animation frame delay always 100 ms

### ISSUE THREAD

**Issue by tjukanovt** [anitagraser/TimeManager#251]
Noticed a small bug in the export dialog. In the latest Time Manager version, the plugin doesn't allow to change the animation frame delay in the export dialog. Or the delay can be changed, but after every click it resets back to 100 ms.

**Comment by anitagraser** [comment]
I assume this affects the animated GIF / video export? Because the simple frame export is always supposed to run as quickly as possible.

**Comment by tjukanovt** [comment]
Yes actually it might be that it works as quickly as possible, but the screen just resets to 100 ms. So I think you can close this one.
