### ISSUE TITLE
ModuleNotFoundError: No module named 'future' 

### ISSUE THREAD

**Issue by dustyaltena** [anitagraser/TimeManager#252]
Getting this error when trying to install Time Manager on QGis 3. I have python 3.6.5 installed, and have uninstalled and reinstalled the future module several times, but cannot get the plugin to install. Any ideas?

> Couldn't load plugin 'timemanager' due to an error when calling its classFactory() method 
> 
> ModuleNotFoundError: No module named 'future'

**Comment by dustyaltena** [comment]
Issue solved. Please ignore.

**Comment by kannes** [comment]
This can be closed. :)

**Comment by kannes** [comment]
Which version of QGIS? Which operating system? Which version of the plugin?

**Comment by fonkamex** [comment]
> Sorry, but I am very new to this and I am lost. I am getting the same error, but I am not sure how to follow the solution above. Could someone please provide more detailed steps to follow?
> Thank you!

If you are using MacOS or Linux open the terminal and write pip3 install future.
If you are using Windows open CMD (DOS terminal) and write pip3 install future.

Do not use the Python console included in QGIS
