### ISSUE TITLE
mktime out of range

### ISSUE THREAD

**Issue by haubourg** [anitagraser/TimeManager#26]
Hi again, 
my dataset raises of range errors. You can find a shapefile here:
http://dl.dropbox.com/u/72368800/step.zip

please test it with  "date_service" as start date and "date_hs" as end date. If "date_hs is null", it means that the feature is still in service. 

here is the error raised at each frame:
  File "C:/Documents and Settings/haubourg/.qgis/python/plugins\timemanager\timemanagerprojecthandler.py", line 34, in writeSetting
    value = mktime(value.timetuple()) # convert datetime to float
OverflowError: mktime argument out of range

I have same errors with postgis data... Maybe date from 0194/01/01 to 2200/01/01 is to large for your float range? 

We need only a frame each year so I put 52 weeks in "Time Frame Size"  

All the best,
Régis

**Comment by carolinux** [comment]
This is fixed now.
