### ISSUE TITLE
The export adds a red cross at 0,0

### ISSUE THREAD

**Issue by stvno** [anitagraser/TimeManager#261]
When exporting a video (or a frame) with Time Manager a red cross is added to the coordinate 0,0. The  projection doesn't matter, it will always add a red cross at the projection's 0-point. I tried it with EPSG:4326, 28992 and 54030.
To be sure it wasn't the data I've created a scratch layer with two points and with the only attribute `date`. And it still added the red cross.
I tested it  both with QGIS 3.2 on ubuntu 18.04 and QGIS 3.0 on windows 10. Both cases the Time Manager was version 3.0.1. 

Below is an export with the two points using the project > export map to image dialog (with the TimeManager filter applied, hence the single point)
![export](https://user-images.githubusercontent.com/394323/46529464-cde84100-c896-11e8-820b-560d43b73336.png)

And here is the first frame of the TimeManager export, notice the red cross
![frame00](https://user-images.githubusercontent.com/394323/46529480-da6c9980-c896-11e8-9c2d-5a80750e0d6b.png)

the scratch layer saved as geojson:
```
{
"type": "FeatureCollection",
"name": "tes2t",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "date": 1 }, "geometry": { "type": "Point", "coordinates": [ -0.055055489035782, 0.072589084270108 ] } },
{ "type": "Feature", "properties": { "date": 12313465 }, "geometry": { "type": "Point", "coordinates": [ -0.117942650609563, 0.0545879264962 ] } }
]
}
```

The TimeManager log
```
2018-10-05T11:59:17     INFO    Plugin language loaded: en
2018-10-05T11:59:17     CRITICAL    Translation file {} for lang {} was not loaded properly,falling back to English
2018-10-05T11:59:17     INFO    TimeManager: $Id$ loaded!
2018-10-05T11:59:54     INFO    Layer extents(datetime.datetime(1970, 1, 1, 0, 0, 1), datetime.datetime(1970, 5, 23, 12, 24, 25))
```

**Comment by stvno** [comment]
I've been diving deeper in the TimeManager code and appears nothing weird is happening in the plugin, it seems that the bug is in QGIS3, when I export my map as image similar to [this](https://github.com/anitagraser/TimeManager/blob/master/timemanagercontrol.py#L377) line, but from the python console I also get a red cross...

**Comment by anitagraser** [comment]
Thanks for debugging! Closing this as upstream issue.
