### ISSUE TITLE
Error creating Video-Export from Time Manager (Ubuntu 18.04) 

### ISSUE THREAD

**Issue by floju** [anitagraser/TimeManager#272]
With ffmpeg installed:

Ein Fehler trat bei der Ausführung von Python-Code auf: 

subprocess.CalledProcessError: Command '['sh', '/home/luca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/animation/video.sh', '/home/luca/Videos/QGIS/frame%04d.png', '/home/luca/Videos/QGIS/out.mp4']' returned non-zero exit status 2. 
Traceback (most recent call last):
  File "/home/luca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/timemanagercontrol.py", line 298, in exportVideo
    animate.make_video(path, self.exportNameDigits)
  File "/home/luca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/animation/animate.py", line 74, in make_video
    subprocess.check_call(["sh", video_script, frame_pattern, outfile])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sh', '/home/luca/.local/share/QGIS/QGIS3/profiles/default/python/plugins/timemanager/animation/video.sh', '/home/luca/Videos/QGIS/frame%04d.png', '/home/luca/Videos/QGIS/out.mp4']' returned non-zero exit status 2.

Python-Version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS-Version: 3.4.2-Madeira Madeira, 5645791 

Python-Pfad:
/usr/share/qgis/python
/home/luca/.local/share/QGIS/QGIS3/profiles/default/python
/home/luca/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/luca/.local/share/QGIS/QGIS3/profiles/default/python
.

**Comment by anitagraser** [comment]
Removed export https://github.com/anitagraser/TimeManager/commit/81abf6c5504f7e1216a65083c074cd46e1f45aea
