### ISSUE TITLE
... argument 1 has unexpected type 'float

### ISSUE THREAD

**Issue by magerlin** [anitagraser/TimeManager#28]
I am getting errors trying to use the Time Manager plugin (version 0.6).
I am running Qgis 1.7.4 Stand alone installer in Win7 64 bit with Python

I 've got a shape file with events  expected to happen in (very) future
years. I have made a text attribute with times like 2034-01-01 00:01:00.000
(only the year part is of interest).

I don't add any End Time or Offset or change any Animation Options in the
"Time Manager settings" window.

The error message:
 File "C:/Users/map/.qgis/python/plugins\timemanager\timemanagerguicontrol.py",
line 343, in updateTimeExtents

self.dock.horizontalTimeSlider.setMaximum(mktime(timeExtents[1].timetuple()))
TypeError: QAbstractSlider.setMaximum(int): argument 1 has unexpected type 'float

Python version: 2.7.2 (default, Jun 12 2011, 15:08:59) [MSC v.1500 32 bit (Intel)]
QGIS version: 1.7.4-Wroclaw Wroclaw, 411aff6

My shape file is here:  https://dl.dropbox.com/u/8189384/Udbygningv5.zip

**Comment by carolinux** [comment]
#77 fixes this, years up to 7999 are supported.
