### ISSUE TITLE
'WMSTRasterLayer' object has no attribute 'resetSubsetString'

### ISSUE THREAD

**Issue by AsgerPetersen** [anitagraser/TimeManager#281]
Plugin version: 3.0.2
QGIS: 3.6.0 on OSX using LutraConsulting installer.

It seems that WMS-T support is broken.

I keep getting this exception:
![image](https://user-images.githubusercontent.com/1392735/54815394-2ae38200-4c92-11e9-97e5-fc39779d361d.png)

A quick fix to get it working with WMS-T is commenting out the failing line.

**Comment by anitagraser** [comment]
Thanks, this was already reported in #256 and fixed but I had a packaging issue. I just uploaded a new zip of the plugin under the same version 3.0.2, so please uninstall and reinstall.

**Comment by AsgerPetersen** [comment]
Ah, I tried searching the issues, but did not think of searching closed issues. Sorry for the noise!

**Comment by anitagraser** [comment]
No worries!
