### ISSUE TITLE
User-friendly error messages are 'eaten' 

### ISSUE THREAD

**Issue by rduivenvoorde** [anitagraser/TimeManager#286]
I'm trying to use a wmst layer as layer, and TimeManager keeps silently failing.

Trying to debug I hit this line:
https://github.com/anitagraser/TimeManager/blob/master/timemanagercontrol.py#L702

Which itself throws a (hidden) error which if I try to evaluate  `traceback.format_exc(e)` during an error throws: ` {TypeError}'>=' not supported between instances of 'NameError' and 'int' ` making that the error is BOTH not seen in the QgsMessagesLog nor shown in a popup dialog because the line beneath it is never reached.
The 'error_msg' already shows me the right message.

If I remove the 'traceback.format_exc(e)' I get a nice popup AND the message is displayed in the messageLog. Should I do a PR?

**Comment by anitagraser** [comment]
@carolinux Do you have insights into the potential consequences?

**Comment by carolinux** [comment]
You can surround the format_exc in a try catch and see if this makes the error display properly @rduivenvoorde

**Comment by anitagraser** [comment]
I've removed `traceback.format_exc(e)` for now to ensure that errors are displayed.

**Comment by anitagraser** [comment]
Now we can at least see an error but all the nice error messages that are coded into time_utils are lost and replaced by useless ones, such as: "An error occurred while trying to add layer "somename" to TimeManager. Cause: '>=' not supported between instances of 'TypeError' and 'int'"

**Comment by rduivenvoorde** [comment]
@anitagraser  are we talking about: https://github.com/anitagraser/TimeManager/blob/master/utils/time_util.py#L314 messages?

Because in my case I've never seen those messages, and I have had quite some failures/errors which never showed an error. 
Maybe "Cause: '>=' not supported between instances of 'TypeError' and 'int'"" is not so nice, but in this case I think it is an indication that there is an issue in the code?

But probably the suggestion of @carolinux is better: instead of the current solution (putting the line in comments):

` #error(error_msg + traceback.format_exc(e))`

surround it with a try catch like this?
```
try:
  error(error_msg + traceback.format_exc(e))
except Exception:
  error(error_msg)
```

@carolinux what you think?

**Comment by anitagraser** [comment]
@rduivenvoorde: Yes, those errors used to appear at some point.

If that code snippet works, let's use it. I tried around a bit on June 9th but without luck.

**Comment by anitagraser** [comment]
@rduivenvoorde Please give https://github.com/anitagraser/TimeManager/tree/bettererrors a try. In my tests, the changes there get rid of "'>=' not supported between ..." errors.

**Comment by anitagraser** [comment]
Mhm, seems like PostGIS layers are broken

**Comment by anitagraser** [comment]
PostGIS layers should work again https://travis-ci.org/anitagraser/TimeManager/builds/606366237?utm_source=github_status&utm_medium=notification
