### ISSUE TITLE
Problem With Map Refresh 

### ISSUE THREAD

**Issue by SpiderMan5445** [anitagraser/TimeManager#290]
Please accept my apologies as I am completely new to this. I am trying to use Time Manager 3.1.0 plugin within QGIS 3.4.4 on Windows 10 Enterprise also tried with version 3.6.1 but seeing the same issue.  When running the animation the WMS map refreshes after each step slowing everything down while waiting for the map to refresh. If I turn off the map layer the plugin runs as expected. I have repeated same exercise with QGIS 2.18 Time Manager 2.5 and same data and all works as expected without the map refreshing all the time. I have zoomed the map to the point data extents just in case.  Another issue is the play button disappears without warning. 

[CSV Data and Log Message.txt](https://github.com/anitagraser/TimeManager/files/3038919/CSV.Data.and.Log.Message.txt)

**Comment by anitagraser** [comment]
Should be fixed by upstream fix https://github.com/qgis/QGIS/pull/10028
