### ISSUE TITLE
Virtual Layer Not working

### ISSUE THREAD

**Issue by gazhay** [anitagraser/TimeManager#292]
Probably I am setting things up wrong, but I cannot get TimeManager to work with my data set.

I created a virtual layer which combined geometries with population data, and the population data is spread over a number of years.

![Shot 012](https://user-images.githubusercontent.com/871127/57883259-945cb880-781d-11e9-84d8-75927ccedcd8.png)

When I add the layer to TimeManager and select either "YearStr" or the text version of "TimeStamp", the timeline control only ever shows "1970-01-01 00:00:00" to "1970-01-01 00:00:00".

Even if I set the time frame start to a valid value, nothing is ever displayed.

Is this a virtual layer problem or a my data problem?

**Comment by anitagraser** [comment]
Duplicates https://github.com/anitagraser/TimeManager/issues/219
