### ISSUE TITLE
Failure to add timestamps in format 2019-06-18T15:09:00.906Z

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#299]
Timestamp format: 2019-06-18T15:09:00.906Z

An error occurred while trying to add layer "somename" to TimeManager. Cause: '>=' not supported between instances of 'TypeError' and 'int'

**Comment by anitagraser** [comment]
Timestamps without letters can be added, e.g. 2019-06-18 15:09:00.906 
but there is a strange effect of the time running backwards while playback is on pause

**Comment by anitagraser** [comment]
Stange because datetime.strptime works as expected:

```
b = datetime.strptime('2019-06-18T15:09:00.906Z', '%Y-%m-%dT%H:%M:%S.%fZ')
b.microsecond
906000
```

**Comment by ferranb** [comment]
The same error happens to me with format HH:MM:SS (military time/24h format) and others. Any clue to debug?

**Comment by ferranb** [comment]
I found the problem. There is a badormed line on the source CSV file

When I add the data to QGis it ignores the wrong line but TimeManager raises the error. Then I guess there is here a improvement on TimeManager to ignore badformed data.
