### ISSUE TITLE
"Ignore this layer when checking if scene is empty" does not work

### ISSUE THREAD

**Issue by Stephocke** [anitagraser/TimeManager#301]
Simple error, the time manager doesnt remember its setting "ignore layer if empty" - "ignorieren als leer erkannt". Just checkmark the attribute, close window, reopen setting window, tm "ignorieren als leer erkannt"/"ignore if empty" is at default setting again.
Hence, Time Manager will export empty pictures because its not able to ignore non-empty layer.
The would be okay, but then this promising option should be removed if it is ignored by Time Manager. I wasted several hours, until I realized that the feature doesnt work.

**Comment by anitagraser** [comment]
Tested and works for me. Please provide test data and your workflow to reproduce.

**Comment by Stephocke** [comment]
I dont know how to provide you my data. The files are to large to attach. 
But this issue doesnt depend on data. Time Manager forgot the setting immediatly after closing the setting window. If i reopen the settings window the marks for this setting disapear.

**Comment by Stephocke** [comment]
![pic1](https://user-images.githubusercontent.com/35409315/59777308-baf68f00-92b4-11e9-9bc6-57fe5bddec96.PNG)
![pic2](https://user-images.githubusercontent.com/35409315/59777309-bb8f2580-92b4-11e9-85e4-9412e7094473.PNG)


There are just 2 clicks between the pictures. 
1. "ok"
2. "reopen"

**Comment by anitagraser** [comment]
I see, so to summarize: the layer option "Ignore this layer when checking if scene is empty" is not applied correctly. The global "Do not export empty frames in time managed layers" works correctly.

**Comment by anitagraser** [comment]
I've investigated this issue and it appears that the implementation of this feature was never completed. I've therefore removed the checkbox from the "Add vector layer" dialog.

**Comment by anitagraser** [comment]
For future reference: the feature was introduced in https://github.com/anitagraser/TimeManager/commit/e0d55fe5bf563b44c3df41242eebcdfb5119e3fc

**Comment by anitagraser** [comment]
I've released a new version. Please give it a try.
