### ISSUE TITLE
GeoPackage date conversion to character and filter

### ISSUE THREAD

**Issue by NTCUser** [anitagraser/TimeManager#303]
I have a layer (geopackage) where I created a column with date format : dates are between 2018-12-20 and 2019-06-20.
I used this column for the time serie. Automatically, the attribute table was filtered with the SQL script : `cast("Date" as character) < '2019/07/20' AND cast("Date" as character) >= '0001/01/01'` (why  2019/07/20 and 0001/01/01 ?) . So the dates were converted to character. But, the Plugin didn't work.

I tried to change manually the dates of the filter script but the plugin reset it.

So, I created a column with character format, copy the dates from de date format column : the plugin works.

What can be the problem with the date format column ?

**Comment by anitagraser** [comment]
Unfortunately GeoPackage and SpatiaLite and SQLite datetime type handling is a mess:

https://github.com/anitagraser/TimeManager/issues/218
https://github.com/qgis/QGIS/issues/30288

**Comment by NTCUser** [comment]
It's working with a Postgis database. Great, thank you.
