### ISSUE TITLE
Play Button Missing on Time Manager 3.2.3 and QGIS 3.8.1

### ISSUE THREAD

**Issue by Housenseederfen** [anitagraser/TimeManager#310]
Hi there, After I have played a sequence on Time Manager the Play Button disappears. Is this normal or have I clicked the wrong button in the settings?  I have seen that I can press where it is usually and it appears

**Comment by anitagraser** [comment]
That should be fixed: https://github.com/anitagraser/TimeManager/issues/291

**Comment by anitagraser** [comment]
I cannot reproduce this issue. Which operating system are you on?

**Comment by anitagraser** [comment]
I think I know what's going on. I'll publish a new version shortly.

**Comment by anitagraser** [comment]
Please try version http://plugins.qgis.org/plugins/timemanager/version/3.2.4/
