### ISSUE TITLE
Exporting GPS coordinates as line on QGIS

### ISSUE THREAD

**Issue by Housenseederfen** [anitagraser/TimeManager#311]
Hi there,

Using data from Movebank I am trying to visualise the path of an animal as a line then export as a jpeg (or a PDF vector line). I have looked online for guides however I can't seem to find a guide for the latest version of QGIS (3.8.1-Zanzibar using on Mac). The headings I have in the CSV file are:

event-id
visible
timestamp
location-long
location-lat
location-error-text
sensor-type
individual-taxon-canonical-name
tag-local-identifier
individual-local-identifier
study-name

Thank you for your help

**Comment by anitagraser** [comment]
Converting track points to track lines is not a TimeManager use case.

Try the **Points to path** tool in the Processing toolbox.
