### ISSUE TITLE
Video from rasters don't export

### ISSUE THREAD

**Issue by quinaia** [anitagraser/TimeManager#313]
How can I export video created through rasters?
How can I eliminate this error code?

Um erro ocorreu enquanto executava o código Python: 

subprocess.CalledProcessError: Command '['C:\\Users\\User\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\timemanager\\animation\\video.bat', 'C:/Users/User/Downloads/video\\frame%02d.png', 'C:/Users/User/Downloads/video\\out.mp4']' returned non-zero exit status 1. 
Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\timemanagercontrol.py", line 299, in exportVideo
    animate.make_video(path, self.exportNameDigits)
  File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\timemanager\animation\animate.py", line 73, in make_video
    subprocess.check_call([video_script, frame_pattern, outfile])
  File "C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\User\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\timemanager\\animation\\video.bat', 'C:/Users/User/Downloads/video\\frame%02d.png', 'C:/Users/User/Downloads/video\\out.mp4']' returned non-zero exit status 1.

**Comment by anitagraser** [comment]
According to https://github.com/anitagraser/TimeManager/issues/160, this can be a symptom of an error exporting the image frames. What files does the```C:/Users/User/Downloads/video``` directory contain?

**Comment by anitagraser** [comment]
Closing for lack of feedback. Reopen if necessary.
