### ISSUE TITLE
Video export fails on Windows 8

### ISSUE THREAD

**Issue by asozio** [anitagraser/TimeManager#314]
When exporting to video (ffmpeg via video.bat) I get the following error

 subprocess.CalledProcessError: Command '['C:\\Users\\xxxxx\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\timemanager\\animation\\video.bat', 'C:/Users/xxxxx/test\\frame%05d.png', 'C:/Users/xxxxx/test\\out.mp4']' returned non-zero exit status 1.

Which appears to occur due to the path format.

Testing the execution of video.bat manually I am able to produce out.mp4

**Comment by anitagraser** [comment]
Probably same as https://github.com/anitagraser/TimeManager/issues/272

**Comment by anitagraser** [comment]
Removed export in https://github.com/anitagraser/TimeManager/commit/81abf6c5504f7e1216a65083c074cd46e1f45aea
