### ISSUE TITLE
Time and Date display

### ISSUE THREAD

**Issue by Cranners47** [anitagraser/TimeManager#327]
Hi, I have been using the Time Manager plugin and it is great, but I have noticed an odd issue.  I use QGIS on my work Laptop which runs Windows 10, my iMac which is running MacOS Catalina and my MacBook, also running MacOS Catalina.  All machines are running The latest stable release of QGIS, 3.12 Bucharest and TimeManager plugin V 3.4, but the issue is this.  On my iMac and Company laptop, when I use the plugin it displays the time and date on top of the map (in the SE corner).  On my Macbook however, I cannot get the time and date to display?  as far as I am aware everything is exactly the same on all 3 machines... same data being used, same settings etc. but my MacBook just refuses to show the time and date? 

Any suggestions?
Image from Windows 10
![Windows 10 Settings](https://user-images.githubusercontent.com/62644953/77524856-fc3d5000-6e7f-11ea-8e1c-29e4beb756e3.jpg)

Image from MacOs (On macBook)
![MacOS Macbook Settings](https://user-images.githubusercontent.com/62644953/77524880-065f4e80-6e80-11ea-97b9-cb85b68811e3.jpg)

**Comment by justinbb** [comment]
I have the same problem (MacBook Pro Retina 13" 2015, macOS Mojave 10.14.6, QGIS 3.12). It seems the date display is being incorrectly placed, so that with most settings it's completely off-screen. If I select placement direction W, the display is in the lower-left corner of the map but so low that only the upper half of the text is visible.

**Comment by anitagraser** [comment]
Since I have no Mac to test, I'll need somebody who does to look into this.

**Comment by Cranners47** [comment]
Ah, I have just tried putting the Time display in the W and it is indeed in the lower left corner... so the time is there as Jusinbb says, its just being displayed in the wrong place.  It doesn't seem to matter what the zoom level is as well.  


![image](https://user-images.githubusercontent.com/62644953/78037111-04572d00-7363-11ea-91cc-25714ecba2c6.png)

**Comment by justinbb** [comment]
Anita, if you can point me to the relevant directory and source files I can take a look and see if I can figure out what's going on. I am not familiar with your code at all, but I am not bad at debugging in general.

**Comment by anitagraser** [comment]
@justinbb This is the function:  https://github.com/anitagraser/TimeManager/blob/73000fc2cdaf8a618038ed80313f7e4aec2205f8/timemanagerguicontrol.py#L572
Thanks for looking into this!

**Comment by justinbb** [comment]
The problem is quite simple: handling [high-DPI displays](https://doc.qt.io/qt-5/highdpi.html). This patch will do the job.

```
--- timemanagerguicontrol-.py	2020-03-30 21:06:47.000000000 -0400
+++ timemanagerguicontrol.py	2020-03-31 17:38:24.000000000 -0400
@@ -587,8 +587,9 @@
                 flags |= flag
 
         # Get canvas dimensions
-        width = painter.device().width()
-        height = painter.device().height()
+        pixelRatio = painter.device().devicePixelRatio()
+        width = painter.device().width()/pixelRatio
+        height = painter.device().height()/pixelRatio
 
         painter.setRenderHint(painter.Antialiasing, True)
         txt = QTextDocument()
```

**Comment by Cranners47** [comment]
AMAZING! that works... Thank you so much!!!

**Comment by justinbb** [comment]
The bug shouldn't be closed yet, because the fix is not yet in the repository. I did not make a pull request because I don't have a branch and the fix is so trivial. Anita, please update the code!

**Comment by Cranners47** [comment]
Ooops, sorry, Didn't realise thats how this works...
