### ISSUE TITLE
Add Timezone support in allowed time formats

### ISSUE THREAD

**Issue by brentfraser** [anitagraser/TimeManager#33]
I’ve got data stored in PostGIS as “timestamps with time zone” e.g.: 2012-04-25 16:05:36-06

**Comment by carolinux** [comment]
OK, I think one way to handle this thing is to just add all the formats
```
%Y-%m-%d %H:%M:%S-06
%Y-%m-%d %H:%M:%S-05
```
etc. With the caveat that you can have only one timezone in your dataset (can't have both +01 and +02 data). I think this is a reasonable assumption...

**Comment by carolinux** [comment]
some timezone support exists now. Please add new issues with specific formats that may not work.

**Comment by csibk** [comment]
Hello,
I also get data from Postgres and the timestamp field is of the type "timestamp with time zone". But my data contains fractional seconds and so TimeManager was unable to add the layer.
After adding
    l.append(fmt + ".%f" + ("-" if i < 0 else "+") + str(abs(i)).zfill(2))
to the function "generate_all_timezones" in time_util.py I can now use my data.
Kind regards
  Christian
