### ISSUE TITLE
Create video/gif programmatically

### ISSUE THREAD

**Issue by bacalfa** [anitagraser/TimeManager#330]
I'm new to QGIS and Time Manager. This is just a question. Is it possible to programmatically generate a video (e.g., .mp4) or gif without opening the GUI? I'm hoping to do something like the following:
- Create a template project with the basic information (e.g., a map image)
- After my Python script finishes certain calculations, create all the data required for the animation (lat/lon, timestamps, flow quantity, etc.)
- Export such data to QGIS/Time Manager for initialization
- Issue a "save video" command with the desired output file name and location
Note that all of the above should be done from a Python script "behind the scenes".

**Comment by anitagraser** [comment]
This is currently not possible and also not planned as a TimeManager feature.
However, it might be possible to achieve something like this by writing a stand-alone PyQGIS script that updates layer filters and exports layouts.
