### ISSUE TITLE
Time frame label placement help

### ISSUE THREAD

**Issue by mkoo** [anitagraser/TimeManager#335]
Hello, attached is a screenshot showing how the labels are not fully visible in the View of QGIS. Settings for Time display options => Placement direction = W 
The map data below are not projected but changing the projection does not help.
(tested in QGIS 3.10 and 3.14, OSX)

The only other direction that works is N-- all others renders the display not viewable; in fact I thought this was not working and have been on the blog, qgis site and this repo seeing if any one else has this issue.  For the life of me, I cannot figure out how to adjust this!

![frame000](https://user-images.githubusercontent.com/2523089/87863676-44dab680-c912-11ea-8779-ccae658c02bb.png)

sorry if this is not actually a bug but user error. Any help is appreciated!

**Comment by anitagraser** [comment]
This ticket seems to be related to #327. Please test the development version from Github.

**Comment by mkoo** [comment]
Just saw this is probably a duplicate issue! Will do.
Thanks

**Comment by anitagraser** [comment]
Please note that since temporal control has now been integrated into QGIS core, this plugin will not be maintained anymore.
