### ISSUE TITLE
TimeManager for Hexbin layers

### ISSUE THREAD

**Issue by lucasvw** [anitagraser/TimeManager#336]
Hi there,

I have a layer with some points and timestamps (from_timestamp and end_timestamp) and I want to visualize a hexbin layer with pointcount of the points inside of the hexagons. And then use TimeManager to see how the hexbin layer changes through time:)

I have tried to create a hexbin layer the "usual" way with MMQGIS and using pointInPolygon.. but then the pointcount get's statically computed once and stored as attribute..

How can I make sure that my hexbin layer get's re-rendered by the TimeManager based on the points that are filtered out at each time instance? Im sure Im not the first person that wants to do this, but can't find any tutorial online so far

Best,
Lucas

**Comment by anitagraser** [comment]
Hi Lucas, 
Please use http://gis.stackexchange.com for support questions. Since temporal control has now been integrated into QGIS core, this plugin will not be maintained anymore.
