### ISSUE TITLE
NULL values in Shapefiles are always displayed

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#5]
Obviously NULL values are always shown. Invalid strings are only noticed, when the layer is registered for management, but are not shown, so it doesn't matter. 

 A check-box in the settings dialogue would be fine: "Show NULL"

http://www.geofrogger.net/trac/ticket/18

**Comment by carolinux** [comment]
Trying to understand how this would work: Let's say, the layer selects the substring:
```
 date<"2014-01-01" date>"2013-12-28"
```
and we have some points with date=NULL. Then I think those points won't be selected by the substring query.

**Comment by anitagraser** [comment]
Each provider will probably handle them a little differently.

**Comment by anitagraser** [comment]
#318
