### ISSUE TITLE
Using time dimention in NetCDF

### ISSUE THREAD

**Issue by sickel** [anitagraser/TimeManager#57]
netcdf is a raster file format used frequently for meteorological data. It can have a time dimention, eg used to show how a weather forcast develops. Presenty, this comes up as a number of bands for the different timesteps - it should be possible to use the time manager to go through the bands. The time steps is also somehow stored in the netcdf, but as a first try, It would be great to just have the time manager to step through the different bands. (I have a working example of a file, but it is large, about 120 megs - I intend to have a look at this and see if I can do something on it)

**Comment by carolinux** [comment]
Can you somehow share this file with me? My gmail handle is carolinegr

**Comment by carolinux** [comment]
@nyalldawson You mentioned in the conference in Nodebo that you have some dataset of this form. Can you share? Thanks

**Comment by nyalldawson** [comment]
Hi Karolina,

Sorry, it took me a while to get hold of one of these. Here's one with a
lot of bands which correspond to different hours throughout a week. You can
see the corresponding time via the layer's metadata - each band has an
associated time value in seconds.

Hope this helps- - and thanks for looking into this!

Nyall

**Comment by carolinux** [comment]
I think github always eats the attachments, can you email it to carolinegr@gmail.com?
Thanks a lot :)

**Comment by carolinux** [comment]
this is now supported for raster layers (in upcoming 2.1 release)
