### ISSUE TITLE
Export doesn't wait for rendering to finish

### ISSUE THREAD

**Issue by Bescu** [anitagraser/TimeManager#62]
I have a problem with the export, a little like the issue #58 but it's not only the timestramp labels that are not exported : in my test-project, my 3 vectors layers aren't exported, and sometimes the rasters basemaps neither.
I've tested the same project on QGis 1.8 and it works.
It looks like a problem with the function "waitAfterRenderComplete" in timemanagercontrol.py.

**Comment by vansman** [comment]
I had the same issue in QGIS 2.6.1. A raster background, two timed vector layers, one with labels, and the frame start time on map. Missing labels, remnants from previous frames/frame skipping, and the frame start time would not always appear. macrojames' solution seemed to solve the problem for me

**Comment by carolinux** [comment]
@vansman, @macrojames Since you have investigated this issue, why do you think mapCanvasRefreshed is better than renderComplete? renderComplete seems to betray its name from what you're saying. :)

**Comment by carolinux** [comment]
This seems to work well.
