### ISSUE TITLE
Add support for joined fields

### ISSUE THREAD

**Issue by dz316424** [anitagraser/TimeManager#66]
While the input layer is joint with other table, the TimeManager seems unable to recognize the additional fields. For example, I have a layer named *aerainfo* joint by another layer name *temporalsirmap_group*. The resulting layer has fields from both layers:
![qq 20140924111629](https://cloud.githubusercontent.com/assets/1726265/4390685/32e824e2-43ff-11e4-9638-450c55b3eede.png)
But the TimeManager only recognizes fields originally in *areainfo* when I tries to add the joint layer.
![qq 20140924111644](https://cloud.githubusercontent.com/assets/1726265/4390758/b157037a-43ff-11e4-8c19-a0ce8d9517ac.png)
It would be pretty handy if there is a direct support for joint fields. Reduce work and save time

**Comment by aroche** [comment]
Support of virtual fields would be nice as well.

**Comment by carolinux** [comment]
@dz316424 , @aroche 
I made a commit which should make this possible. Please test out the current master
 d413b7173a63495dc866511d
and tell me if this works for you :)

**Comment by anitagraser** [comment]
I can see joined and virtual fields but using the virtual fields throws 

<code>
Traceback (most recent call last):
  File "C:/Users/anita/.qgis2/python/plugins\timemanager\timemanagercontrol.py", line 459, in readSettings
    restore_function(setting_value)
  File "C:/Users/anita/.qgis2/python/plugins\timemanager\timemanagercontrol.py", line 510, in restoreTimeLayers
    self.timeLayerManager.registerTimeLayer(timeLayer)
  File "C:/Users/anita/.qgis2/python/plugins\timemanager\timelayermanager.py", line 151, in registerTimeLayer
    self.refreshTimeRestrictions()
  File "C:/Users/anita/.qgis2/python/plugins\timemanager\timelayermanager.py", line 135, in refreshTimeRestrictions
    timeLayer.setTimeRestriction(self.getCurrentTimePosition(),self.timeFrame())
  File "C:/Users/anita/.qgis2/python/plugins\timemanager\timevectorlayer.py", line 220, in setTimeRestriction
    raise SubstringException("Could not update subset string for layer {}. Tried: {}".format(self.layer.name(), tried))
SubstringException: Could not update subset string for layer area. Tried: ['date_start = 1420070400 ', 'date_start = 1420070400 ']

</code>

The virtual fields are strings with 2015-01-01 to 2015-01-06 values.

**Comment by carolinux** [comment]
@anitagraser Send me your project file. Joined fields works?

**Comment by carolinux** [comment]
O wow :D This looks like a bug in the handling of virtual fields in qgis core itself->
'''
self.getProvider().uniqueValues(7)
[u'2014-02-05']
 self.getProvider().minimumValue(7)
0.0 # what?
'''

**Comment by carolinux** [comment]
The doc says "A virtual field will be recalculated every time it is used. Its definition will be saved in the project file. It will not be saved in the dataprovider and therefore its values not be available in other software."

It seems to be partially true in practice.

**Comment by anitagraser** [comment]
"A virtual field will be recalculated every time it is used." wouldn't be a problem imho. I think this line just wants to say that the changes are not saved back to file/db.

**Comment by carolinux** [comment]
Yeah of course, but we take the values from the dataProvider() generally. I
need to figure out how to get them when they're not there.

**Comment by voszp** [comment]
Support for joined fields is probably not working correctly in QGIS 2.8.3

After joining an EXCEL- and a shapefile one-on-one I can add appropriate start attributes in TimeManager but nothing is shown in the main window after starting the plugin.

Where can I send my project files?

**Comment by carolinux** [comment]
Send the excel, and project file and shapefile to carolinegr@gmail.com

**Comment by carolinux** [comment]
I tried your data, seems like QGIS can't set the subset string properly on the joined fields for some reason (but it doesn't throw an error either). Looks like it's a problem with QGIS core.
