### ISSUE TITLE
Shapefile Date 'D' Fields Fail OGR Query

### ISSUE THREAD

**Issue by riggsd** [anitagraser/TimeManager#71]
ESRI Shapefiles, which use dBase files for feature storage, support storing fields of type Date ('D'). These values are stored on disk as an 8-byte ASCII 'YYYYMMDD' field. QGIS parses their values out as a QDate object. 

It looks like TimeManager 1.2.1 auto-detects these values and attempts to use them, BUT it turns out that the layer filtering only has year-level granularity. This bug is due to the way the OGR query is interpreted. With TimeManager enabled, I see that the "Feature subset" query for one of my layers is:

```
cast("STARTDATE" as character) < '2004-11-26' AND cast("ENDDATE" as character) >= '2004-11-26' 
```

So TimeManager constructs this query such that a string representation of the value is compared to a specified date value, also a string. Comparing string-to-string means we are comparing date strings lexicographically.

When I examine the values in these 'D' type fields in the QGIS Attribute Table, it renders the values to string in the form "2014-12-03", which should compare correctly in the above OGR SQL query, right? Ah, but the Attribute Table shows us QGIS's QDate, the SQL query runs in OGR.

Let's see what OGR thinks about these fields:

```
# print the value of STARTDATE field (and a cast to string) for first object
$> ogrinfo -q mylayer.shp -sql 'SELECT "STARTDATE", cast("STARTDATE" as character) FROM "mylayer"' -fid 0

Layer name: mylayer
OGRFeature(mylayer):0
  DATE (Date) = 2002/02/09
  FIELD_2 (String) = 2002/02/09
  LINESTRING (637808.807291585952044 4289358.298181599937379 653.27784,637808.630513385636732 4289357.508755082264543 653.134584)
```

Ah, so OGR casts a Date object to string in "YYYY/MM/DD" format, which we CANNOT compare lexicographically to a string of "YYYY-MM-DD" format, as TimeManager does.

I locally modified the query in `timevectorlayer.py` to replace the '-' chars with '\' for our timeslice bounds, like this:

```python
    def constructOGRSubsetString(self, startTime, endTime):
        """Constructs the subset query depending on which time format was detected"""
        startTime, endTime = startTime.replace('-', '/'), endTime.replace('-', '/')  # hack for Shapefile 'D' field
        if self.timeFormat[0:2] == '%Y' and self.timeFormat[3:5] == '%m' and self.timeFormat[6:8] == '%d':
            return "cast(\"%s\" as character) < '%s' AND cast(\"%s\" as character) >= '%s' " % ( self.fromTimeAttribute,endTime,self.toTimeAttribute,startTime)
        ...
```

And NOW the selections work when I step TimeManager daily or monthly. 

So, the above is not a general patch to fix the problem, but at least identifies what and where the problem is.

Summary: ESRI Shapefile Date columns (type 'D') are read into OGR as OGR's Date type. TimeManager casts values to string when composing its per-timeslice SQL query. When OGR casts its Date type to string, it does so in a format (YYYY/MM/DD) incompatible with the SQL query TimeManager currently builds (YYYY-MM-DD), causing TimeManager to have only per-year granularity with these fields.

**Comment by carolinux** [comment]
Right now I came across a shapefile(ESRI shapefile it says) with QDates that doesn't turn into the yyyy/mm/dd thing when cast as a character within qgis! It is yyyy-mm-dd instead. For this, the fix doesn't work. 

Any idea what happened? Are there different *shapefile* standards? When I try to query this file with ogrinfo, I need to use slashes, but when I use this shapefile with TimeManager, it would work perfectly only with dashes...

**Comment by anitagraser** [comment]
No clue honestly. Sounds like something that would be within the responsibility of OGR.

**Comment by carolinux** [comment]
I'm just curious, yeah. I can't find any file with the old behavior (ie y/m/d) at the moment.

**Comment by riggsd** [comment]
Can you post the output of this command?

`ogrinfo -so myfile.shp -sql 'SELECT * FROM myfile'`

Does the field in question have data type `Date (10.0)`, which is what the .DBF standard requires for a true date field?

**Comment by carolinux** [comment]
No, it says: DATE: Real (12.0)
In the meantime I found another file with the old behavior and it says: Date (10.0)

**Comment by riggsd** [comment]
It sounds like your "DATE" field is not a valid Shapefile type 'D' date, and does not apply to this GitHub issue.

The .DBF file, for a true "date" datatype, must have type 'D', be 8 bytes in width, with equivalent Python format of `%Y%m%d`. 

See: http://www.dbase.com/KnowledgeBase/int/db7_file_fmt.htm

Are your observed date _values_ way off? I believe that if Time Manager can cast a value to `int()`, it will interpret the value as a UNIX timestamp, likely putting your dates into the 1970's.

**Comment by carolinux** [comment]
I'm one of the developers of Time Manager, I am mostly interested in how to detect the difference between those two things, because when TimeManager reads it, the type it gets is Qdate and the provider type in both cases is "ESRI shapefile". :)

**Comment by riggsd** [comment]
I don't mean to offend, and you certainly know the TimeManager code better than I!

My point was simply that the root of issue #71 is related to building a SQL query from an OGR Date type cast as string. Your ESRI Shapefile, whether intended or not, is not using an OGR Date type, as shown from the output of `ogrinfo`. Your field is of one of the OGR numeric types, which is why I mentioned the Unix timestamp behavior. Perhaps the problem could be a regression from this #71 fix, but it doesn't sound as if it is caused by the same root problem. :-)

**Comment by carolinux** [comment]
Yeah, no offense taken. I'm just pondering how to keep #71 and not apply it more than I should. Right now if the time attribute is of type qdate or qdatetime, I use the logic in #71, but clearly this was a misunderstanding on my part - not all of the stuff that qgis eventually sees as qdates is handled the same.

**Comment by carolinux** [comment]
Also, I made a mistake, the column that doesnt work is DATE_FIN: Date (10.0) 
ie, also a date
