### ISSUE TITLE
Support delimited text files

### ISSUE THREAD

**Issue by anitagraser** [anitagraser/TimeManager#79]
Seems like OGR now supports subset query strings for delimited text layers but there is currently a syntax error thrown when text layers are added to Time Manager. (Tested with a file with DD-MM-YYYY HH:MM timestamp.)

**Comment by carolinux** [comment]
Delimited text files with integer timestamps work, but yes text timestamps seem to have some problem with setting the subsetString

**Comment by carolinux** [comment]
Seems like the Postgres syntax works for delimited text files and not the OGR syntax.

**Comment by carolinux** [comment]
4d8ee52
fixes this. Also added test file
