### ISSUE TITLE
Trouble animating more than one layer on OS X

### ISSUE THREAD

**Issue by patagonian** [anitagraser/TimeManager#80]
I am using Time Manager to animate some animal tracking data, and I have been unable to animate more than one layer simultaneously on a Mac (or to animate the same layer twice, which actually is useful in certain contexts).  I am using QGIS 2.6 (Brighton) on a brand-new Macbook Pro running OS X 10.10, but the plugin also failed on QGIS version 2.4 on a slightly older Mac running OS X 10.8.5.  Sometimes it crashes Time Manager and sometimes QGIS crashes.  Sometimes the second layer doesn't show, or results are bizarre.  My data sets are big, and maybe it would work for a smaller data set.  It seems from your blog posts as though it works on Windows, but I haven't tried Windows myself.

**Comment by carolinux** [comment]
Try the newest version (by checking out from this repository)
Animation signals were caught in a loop before, which may have worked differently on different operating systems.

**Comment by carolinux** [comment]
WIll reopen if necessary! Please test with latest master.
