### ISSUE TITLE
Feature request -- error messsage

### ISSUE THREAD

**Issue by patagonian** [anitagraser/TimeManager#81]
When you "Export Video," on a Mac some of the lower-level folders require permission by default (e.g., my root folder, /Users/John), and if you try to put the video there, you get an "Export Complete!" message, but no files are created.  It would be nice if there was an error message when that happened, because it was tricky to figure out why it didn't work.

**Comment by carolinux** [comment]
Now there should be an exception if the area is unwritable.

**Comment by carolinux** [comment]
#77 addresses this
