### ISSUE TITLE
Support for YYYY-MM-DDTHH:MM:SS timestamp format

### ISSUE THREAD

**Issue by henrikkriisa** [anitagraser/TimeManager#83]
I would appreciate if support is added for the YYYY-MM-DDTHH:MM:SS format (e.g T as separator between date and time) for the Time Manager plugin.

**Comment by carolinux** [comment]
Do you have a sample file you can give us @henrikkriisa to verify the implementation?

Thanks :)

**Comment by henrikkriisa** [comment]
Here is an example SQLite file. Thanks :)

**Comment by henrikkriisa** [comment]
I don't know on how to attach example files to this issue on GitHub. Can someone please help me?

**Comment by carolinux** [comment]
Just email it to me carolinegr@gmail.com. 
Another way would be to share it via a dropbox link, but just email should work.
Thanks. :)

**Comment by henrikkriisa** [comment]
Ok, here is a test file. /Henrik

**Comment by carolinux** [comment]
didn't receive anything. Please send it explicitly to carolinegr@gmail.com as opposed to attaching it when you reply to github-notification email

**Comment by carolinux** [comment]
received now

**Comment by carolinux** [comment]
new master works with this file.

d5c6bbf619c7941270

**Comment by carolinux** [comment]
No need to specify a format when loading the layer also.

**Comment by henrik** [comment]
Mentioned the wrong Henrik :) I'll unsubscribe myself from the thread.

**Comment by henrikkriisa** [comment]
Unfortunately, I'm not getting any success with the 1.4.1 version with my VRT connected database file, see error message here:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/Users/henrik/.qgis2/python/plugins/timemanager/timemanagerguicontrol.py", line 229, in saveOptions
    if self.createTimeLayer(row):
  File "/Users/henrik/.qgis2/python/plugins/timemanager/timemanagerguicontrol.py", line 281, in createTimeLayer
    timeFormat,offset, self.iface)
  File "/Users/henrik/.qgis2/python/plugins/timemanager/timevectorlayer.py", line 34, in __init__
    self.timeFormat = getFormatOfDatetimeValue(self.getMinMaxValues()[0], hint=str(timeFormat))
  File "/Users/henrik/.qgis2/python/plugins/timemanager/time_util.py", line 134, in getFormatOfDatetimeValue
    raise Exception("Could not find a suitable time format for value {}, choices {}".format(datetimeValue, formatsToTry))
Exception: Could not find a suitable time format for value 2014-01-01T00:00:01, choices ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%Y/%m/%d %H:%M:%S.%f', '%Y/%m/%d %H:%M:%S', '%Y/%m/%d %H:%M', '%Y/%m/%d', '%d.%m.%Y %H:%M:%S.%f', '%d.%m.%Y %H:%M:%S', '%d.%m.%Y %H:%M', '%d.%m.%Y', '%d-%m-%Y %H:%M:%S.%f', '%d-%m-%Y %H:%M:%S', '%d-%m-%Y %H:%M', '%d-%m-%Y', '%d/%m/%Y %H:%M:%S.%f', '%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M', '%d/%m/%Y']


Python version:
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]


QGIS version:
2.6.1-Brighton Brighton, 

Python path: ['/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/henrik/.qgis2/python', u'/Users/henrik/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools', '~/.qgis/python', '.']

**Comment by anitagraser** [comment]
Imho, wrong time field format errors should be explained in a popup rather than by just throwing a Python error.

**Comment by henrikkriisa** [comment]
I'm now able to use the Time Manager after modifying two files:

1) timevectorlayer.py, line 175 to:
        return "\"%s\"  < '%s' AND \"%s\" >= '%s' " % \

instead of 

return "cast(\"%s\" as character) < '%s' AND cast(\"%s\" as character) >= '%s' " % \

and 

2) timeutil.py

with addition on line 22:

"%Y-%m-%dT%H:%M:%S"

**Comment by carolinux** [comment]
Hello,
VRT is apparently a format which follows the PostGIS query model. First time I hear of this format. I think the sqlite file should have worked without adding anything to the time_util too. However, it doesnt hurt to have this format as supported since this is the default string representation of sqlite dates. Feel free to do a PR for TimeManager with that (including only time_util though)

**Comment by carolinux** [comment]
This should work now with the overhauled query system (spatialite file support + support for the text format of spatialite)
