### ISSUE TITLE
Time Manager load error: NoneType object has no attribute 'split'

### ISSUE THREAD

**Issue by henrikkriisa** [anitagraser/TimeManager#87]
When starting QGIS with the latest 1.4 time manager QGIS crashes with the following error:

Couldn't load plugin timemanager due an error when calling its classFactory() method  
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 208, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/henrik/.qgis2/python/plugins/timemanager/__init__.py", line 5, in classFactory
    return timemanager(iface)
  File "/Users/henrik/.qgis2/python/plugins/timemanager/timemanager.py", line 45, in __init__
    lang=locale.getdefaultlocale()[0].split("_")[0]
AttributeError: 'NoneType' object has no attribute 'split'
 Python version: 2.7.6 (default, Sep  9 2014, 15:04:36)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]   QGIS version: 2.6.1-Brighton Brighton,   Python path: ['/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/henrik/.qgis2/python', u'/Users/henrik/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', '~/.qgis/python']

(I'm running QGIS on Mac OS X 10.0.1 Yosemite)

**Comment by anitagraser** [comment]
For a temporary solution - until an update is released - you can remove the <code>.split("_")[0]</code> part from this line.

**Comment by carolinux** [comment]
Alright, gotta fix this on Mac.

**Comment by carolinux** [comment]
9e7381164 
fixes this
Try setting the lang var to "en"

**Comment by anitagraser** [comment]
updated http://plugins.qgis.org/plugins/timemanager/version/1.4.1/

**Comment by carolinux** [comment]
Thanks :)
And sorry for leaving that in. I didn't think it was possible for the locale would to be non-set somehow.
