### ISSUE TITLE
Error after updating the plugin when creating a new project 

### ISSUE THREAD

**Issue by luipir** [anitagraser/TimeManager#94]
Hi,

I Update the plugin leaving it deactivated. I started to have errors cleaning a project that come form the plugin

sorry is not an up to date master compilation where I found this issue... and in this moment I've not time to align the code.

because the error append when the plugin is not ative => I think should be come from some modification in the __init__ of the plugin always loaded by qgis during startup.
***************
this is the emitted exception:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/ginetto/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 64, in restoreDefaults
    self.setTimeFrameType('days')
  File "/home/ginetto/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 295, in setTimeFrameType
    self.writeSettings()
  File "/home/ginetto/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 308, in writeSettings
    (timeLayerManagerSettings,timeLayerList) = self.timeLayerManager.getSaveString()
  File "/home/ginetto/.qgis2/python/plugins/timemanager/timelayermanager.py", line 272, in getSaveString
    datetime_to_str(self.projectTimeExtents[0], tdfmt)
  File "/home/ginetto/.qgis2/python/plugins/timemanager/time_util.py", line 65, in datetime_to_str
    if dt.year>=1900:
AttributeError: 'NoneType' object has no attribute 'year'

Python version:
2.7.3 (default, Mar 13 2014, 11:26:58) 
[GCC 4.7.2]

QGIS version:
2.7.0-Master Master, aa4338a

Python path: ['/home/ginetto/.qgis2/python/plugins/processing_workflow', '/home/ginetto/.qgis2/python/plugins/processing_prepair', '/home/ginetto/.qgis2/python/plugins/processing_circuitscape', '/home/ginetto/PROGRAMMING/QGIS-2.0-master/build/output/python/plugins/processing', '/home/ginetto/.qgis2/python/plugins/permaclim', '/home/ginetto/.qgis2/python/plugins/processinglwgeomprovider', '/home/ginetto/.qgis2/python/plugins/pstools', '/home/ginetto/.qgis2/python/plugins/processing_gpf', '/mnt/data/PROGRAMMING/FAUNALIA/qgis-plugins/rt_geosisma_offline/libraries', '/mnt/data/PROGRAMMING/FAUNALIA/qgis-plugins/rt_geosisma_offline', '/home/ginetto/PROGRAMMING/QGIS-2.0-master/build/output/python', u'/home/ginetto/.qgis2/python', u'/home/ginetto/.qgis2/python/plugins', '/home/ginetto/PROGRAMMING/QGIS-2.0-master/build/output/python/plugins', '/usr/local/lib/python2.7/dist-packages/setuptools-0.7.5-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/logilab_astng-0.24.3-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/logilab_common-0.59.1-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/pyspatialite-3.0.1_alpha_0-py2.7-linux-x86_64.egg', '/usr/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/pip-1.5.1-py2.7.egg', '/mnt/data/PROGRAMMING/QGIS-2.0-master/build/output/python/qgis', '/home/ginetto/.qgis2/python/plugins', '/mnt/data/PROGRAMMING/IDE/Aptana_Studio_3/plugins/org.python.pydev_3.8.0.201409251235/pysrc', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PIL', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', '/home/ginetto/.qgis2/python/plugins/MetaSearch/ext-libs', '/home/ginetto/PROGRAMMING/QGIS-2.0-master/build/output/python/plugins/fTools/tools', '/home/ginetto/.qgis2/python/plugins/DigitizingTools/tools', '/home/ginetto/.qgis2/python/plugins/midvatten', '/home/ginetto/.qgis2/python/plugins/mmqgis/forms', '~/.qgis/python']

**Comment by carolinux** [comment]
replace the line that throws the error:

```
datetime_to_str(self.projectTimeExtents[0], tdfmt)
```

with 
```
datetime_to_str(self.projectTimeExtents[0], tdfmt) if self.projectTimeExtents[0] is not None else ""
```

**Comment by luipir** [comment]
uninstalling the plugin, continue to create errors => probably ther is not a correct upload implementation

this is the exception cleaning a project after uninstalled the plugin
*********************
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/home/ginetto/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 64, in restoreDefaults
  File "/home/ginetto/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 295, in setTimeFrameType
  File "/home/ginetto/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 308, in writeSettings
  File "/home/ginetto/.qgis2/python/plugins/timemanager/timelayermanager.py", line 272, in getSaveString
  File "/home/ginetto/.qgis2/python/plugins/timemanager/time_util.py", line 65, in datetime_to_str
AttributeError: 'NoneType' object has no attribute 'year'

**Comment by carolinux** [comment]
Please see the workaround I posted. Thanks for reporting this. :)

**Comment by carolinux** [comment]
fixed in current master

**Comment by luipir** [comment]
better leave reference to the commit

thank you to fix it :)

**Comment by carolinux** [comment]
97f8f395c8387a2 is the commit
