### ISSUE TITLE
Time manager issue on Project→New exiting and saving project

### ISSUE THREAD

**Issue by marcobra** [anitagraser/TimeManager#96]
On Ubuntu 14.04 64bits with
QGIS:2.6.1-Brighton Brighton, exported
Python:2.7.6 (default, Mar 22 2014, 23:03:41) [GCC 4.8.2]

What i do:
Select new project
On exit open project saving changes...
time manager crash, BTW never used on this project
Before send this report i test on several single shapes, same issue only on "Project→new"

Closing qgis saving changes do not show any timemanager issue

Thanks
Marco

Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 64, in restoreDefaults
    self.setTimeFrameType('days')
  File "/home/ubuntu/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 295, in setTimeFrameType
    self.writeSettings()
  File "/home/ubuntu/.qgis2/python/plugins/timemanager/timemanagercontrol.py", line 308, in writeSettings
    (timeLayerManagerSettings,timeLayerList) = self.timeLayerManager.getSaveString()
  File "/home/ubuntu/.qgis2/python/plugins/timemanager/timelayermanager.py", line 272, in getSaveString
    datetime_to_str(self.projectTimeExtents[0], tdfmt)
  File "/home/ubuntu/.qgis2/python/plugins/timemanager/time_util.py", line 65, in datetime_to_str
    if dt.year>=1900:
AttributeError: 'NoneType' object has no attribute 'year'

**Comment by carolinux** [comment]
Try the current master.
This is a known issue and we will release version 1.5 soon which fixes it!

**Comment by marcobra** [comment]
Tested master dl from git and i confirm there are no more this issue...

- Removed fom qgis the installed one, quit qgis

```
cd ~/.qgis2/python/plugins
git clone https://github.com/anitagraser/TimeManager.git
```
- restarted qgis, made test 

Thank
Marco

**Comment by carolinux** [comment]
awesome, thanks!

**Comment by marcobra** [comment]
I leave commit reference i tested here is 
```
cd ~/.qgis2/python/plugins/TimeManager
git rev-parse HEAD 
a2200f2ebb13faf501b56c75b9ddbd16775ec347

```
regards
Marco

**Comment by marcobra** [comment]
Commit head reference tested here is:
```
cd ~/.qgis2/python/plugins/TimeManager
git rev-parse HEAD 
a2200f2ebb13faf501b56c75b9ddbd16775ec347

```
Thanks
Marco
